### ISSUE TITLE
Java classes generated from protobuf are deleted

### ISSUE THREAD

**Issue by mioalter** [neoclide/coc-java#100]
Hi,

I am working in a maven project that contains protobuf which generate java classes. If run`mvn clean compile`, then `ls` the directory of generated classes, I see they have been successfully generated. If I then start nvim and open the project, JDT starts and does its stuff, but now if I`ls` the directory containing the generated java files again, I find that it no longer exists. I can still see the names of generated java source files in NERDTree, but cannot open them and in files in my project that import them, the imports cannot be resolved.

In contrast, if I leave the project open in nvim in one tab and in another rerun `mvn clean compile` and `ls` the directory of generated classes to confirm that it exists, when I switch back to nvim, I can now open the generated java classes and they can be imported successfully elsewhere in the project. Unsurprisingly, if I `ls` the directory of generated classes now, it still exists.

Any tips on what might be causing this and how to avoid it?

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by salarkhan** [comment]
seeing this as well for java. for future folks hitting the same issue:

```
[Warn  - 1:17:05 PM] Apr 9, 2021, 1:17:05 PM Synchronize project com_github_census_instrumentation_opencensus_proto failed due to an error connecting to the Gradle build.
Could not run build action using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-4.9-bin.zip'.
org.gradle.tooling.GradleConnectionException: Could not run build action using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-4.9-bin.zip'.
...
... <stacktrace here>
...
Caused by: org.gradle.api.GradleException: Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the user guide chapter on the daemon at https://docs.gradle.org/4.9/userguide/gradle_daemon.html
Please read the following process output to find out more:
-----------------------

FAILURE: Build failed with an exception.

* What went wrong:
java.lang.ExceptionInInitializerError (no error message)
```

while the rest of the errors are due to being unable to find the file.
