### ISSUE TITLE
Improve doHover float.

### ISSUE THREAD

**Issue by BonaBeavis** [neoclide/coc-java#102]
Momentarily the hover float looks like this:

![image](https://user-images.githubusercontent.com/3330855/88799822-5db35980-d1a7-11ea-9919-6419da2af8cc.png)

I would like to improve the following:
1. Enable concealment for links
2. Also enable concealment for **etc**
3. Make the links clickable

Does anyone has some pointers how to achieve this? Concealment option do have no effect, is this a bug?

**Comment by chemzqm** [comment]
PR welcome

**Comment by BonaBeavis** [comment]
I looked into it and found a lot of complexity for [setting a Document in a float window.](https://github.com/neoclide/coc.nvim/blob/fa536851f83a0edd776ed3972509d1c66fa65e33/src/model/floatBuffer.ts#L27). I think this is because  in earlier lsp specs, the `textDocument/hover` returned `MarkedStrings`, which could have been in any language. But with `MarkupContent`, the language is either "plaintext" or "markdown". If the client returns `MarkupContent`, can we just let vim and plugins handle the syntax highlighting and concealment? For example [vim-markdown](https://github.com/plasticboy/vim-markdown#fenced-code-block-languages) supports even fenced codeblocks.

**Comment by chemzqm** [comment]
It was improved.
