### ISSUE TITLE
Support for java.configuration.runtimes required.

### ISSUE THREAD

**Issue by atsiporu** [neoclide/coc-java#103]
Please introduce support for java.configuration.runtimes to allow compilations on different JVM then JVM the language server was started on.
This is useful when working with projects that must be build on older java versions.
Thank you.

**Comment by atsiporu** [comment]
As a work around, I am currently running coc-java with "java.autobuild.enabled": false
and I am running a separate eclipse process with autobuild true that builds my project with configured jre.

**Comment by dansomething** [comment]
While not yet officially supported in the configuration contributed by this plugin, you may still set `java.configuration.runtimes` in your coc settings using [CocConfig](https://github.com/neoclide/coc.nvim/wiki/Using-the-configuration-file#opening-the-configuration-file) or [CocLocalConfig](https://github.com/neoclide/coc.nvim/wiki/Using-the-configuration-file#configuration-file-resolve). It will get [passed through](https://github.com/neoclide/coc-java/blob/master/src/index.ts#L127) to the language server.

**Comment by atsiporu** [comment]
Thank you
