### ISSUE TITLE
Java 11 is now required

### ISSUE THREAD

**Issue by ismaelgv** [neoclide/coc-java#106]
It seems that it now requires Java 11 to run this language server:
https://github.com/eclipse/eclipse.jdt.ls#first-time-setup

I noticed this after having some problems with the latest downloaded version running with Java 8. I found this in the logs:
```
!ENTRY org.eclipse.jdt.ls.core 4 0 2020-08-05 19:26:38.247
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.jdt.ls.core [47]
  Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"
```

After setting Java 11 as my default Java version everything is working fine again.

**Comment by dansomething** [comment]
This was changed in jdt.ls [version 0.59.0](https://github.com/eclipse/eclipse.jdt.ls/blob/master/CHANGELOG.md#0590-july-22nd-2020).

As a temporary workaround you may also use a [previous version](https://download.eclipse.org/jdtls/milestones/) of jdt.ls. Another option is to use the [`java.home` setting](https://github.com/neoclide/coc-java#setting-the-jdk) to start jdt.ls with Java 11+. There is also the [`java.configuration.runtimes` setting](https://github.com/neoclide/coc-java/issues/103) to support building projects which require Java 8.

**Comment by ChuckDaniels87** [comment]
I did not know about `java.configuration.runtimes`, tha nks for the tip!
