### ISSUE TITLE
Format ignores textwidth while breaking lines

### ISSUE THREAD

**Issue by ozars** [neoclide/coc-java#108]
`format` command doesn't seem to play well with `textwidth`. I think it would be better if vim's `textwidth` is used as a default value for LSP's `lineSplit` if it isn't explicitly set, or the former takes the latter's value otherwise.

### CocInfo

```
## versions

vim version: VIM - Vi IMproved 8.2 8020716
node version: v12.18.2
coc.nvim version: 0.0.78-bdd9a9e140
coc.nvim directory: /home/omer/dotfiles/vim/plugged/coc.nvim
term: dumb
platform: linux

## Output channel: highlight

[Info  - 3:24:36 PM] Highlight server running in node v12.18.2

## Output channel: java

[Info  - 3:24:38 PM] JDT Language Server started
[object Object]



```

### java.open.serverLog

https://gist.github.com/ozars/dc6c05ceac1c29328305184d0214c8ec

### mini.vim

```vim
set nocompatible
set runtimepath=/home/omer/.vim/plugged/coc.nvim
filetype plugin indent on
syntax on
set hidden
set showcmd

set tabstop=4 softtabstop=4 shiftwidth=4 expandtab

set ruler
set textwidth=100
set colorcolumn=+1
set filetype=java
```

### Format.java

```java
class Format {
    @SuppressWarnings("unused")
    public static void Test(String[] args, int v1, int v2, int v3, int v4, int v5, int v6, int v7, int v8) {
        int longVarName1, longVarName2, longVarName3, longVarName4, longVarName5, longVarName6, longVarName7, longVarName8, longVarName9;
        var str = "Hello";
        System.out.println(str);
    }
}
```

### Run

```
vim -u mini.vim Format.java
```

### Before `:call CocAction("format")`

![image](https://user-images.githubusercontent.com/13993759/89944748-f2757880-dbe5-11ea-8d6d-84492ac488dd.png)

### After  `:call CocAction("format")`

![image](https://user-images.githubusercontent.com/13993759/89944930-323c6000-dbe6-11ea-8eba-dab7a62fd753.png)

**Comment by chemzqm** [comment]
Read doc of jdtls for how you could specify format options

**Comment by ozars** [comment]
> Read doc of jdtls

`textwidth` is a vim option. How could an LSP could know about it without coc-java letting it know?
