### ISSUE TITLE
How to trigger code format

### ISSUE THREAD

**Issue by strogiyotec** [neoclide/coc-java#113]
Good day, it's probably nooby question but I can't figure out how to trigger code format.

Readme says that it's supported  `Code formatting (on-type/selection/file)`. So here is my settings.json for it

```
{
		"java.format.enabled": false,
		"java.completion.guessMethodArguments": true,
		"java.format.settings.url": "https://raw.githubusercontent.com/google/styleguide/gh-pages/eclipse-java-google-style.xml"
}
```
According to docs `java.format.enabled : Enable/disable the default Java formatter.` so I think that I disabled default formater and enabled formatter from eclipse, now how to trigger code formatting ? I assume it should be triggered by saving the file but it won't. Did I miss this information from the doc ? Thank you in advance

**Comment by chemzqm** [comment]
Search format in doc of coc.nvim.

**Comment by LordMZTE** [comment]
I've actually not gotten the formatter to work. Running to command `:CocAction format` results in a `[coc.nvim] No format code action available` message. The rest of coc-java is working fine tho.

**Comment by chemzqm** [comment]
it's function, learn viml first.
