### ISSUE TITLE
show_documentation not opening popup anymore.

### ISSUE THREAD

**Issue by johannboehme** [neoclide/coc-java#115]
Built vim + coc.nvim from source yesterday.

![Popup on completion](https://user-images.githubusercontent.com/58803954/94014168-79a03980-fdab-11ea-9b48-f1e0fbbef00c.png)
Popups on completion are working as always.

But showing the documentation for the token under the curser doesn't work anymore.
The mapping is ok (coc.nvim standart config)
![Mapping is active](https://user-images.githubusercontent.com/58803954/94014320-a9e7d800-fdab-11ea-95f5-f89f72527f06.png)

:messages did not show any errors:
![image](https://user-images.githubusercontent.com/58803954/94045870-3f955e80-fdd0-11ea-8331-52a34f3bfc65.png)

I am running on WSL2 and tried to replicate the error on a fresh Ubuntu and a Debian instance.
I installed nothing on the fresh instance besides the required packages: JDK, Node, Vim, coc.nvim (didn't even include additional plugins) and coc-java.
I could confirm the missing documentation window in both environments.
[Edit: Could also find that behavior in both vim (8.2) and nvim (0.5.0)]
Other language server (tested JS + python) still show it.

Would be really grateful some tipps on how to analyse this further!

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.
