### ISSUE TITLE
JDT starts, but no error or warning diagnostics are shown

### ISSUE THREAD

**Issue by LanHikari22** [neoclide/coc-java#116]
## Description
Trying to use coc-java on a maven springboot application, but no errors or warnings are displayed. Jump to definition and autocomplete do work however. 

## Context
- Relevant dotfiles:
  - https://github.com/LanHikari22/lan-dotfiles/blob/master/vimrc
  // only contains ccls information
  - https://github.com/LanHikari22/lan-dotfiles/blob/master/coc-settings.json
- JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
- Output of `:CocInfo`:
```
## versions

vim version: VIM - Vi IMproved 8.2 8021539
node version: v8.10.0
coc.nvim version: 0.0.79-6cb5c6cd2d
coc.nvim directory: /home/lan/.vim/plugged/coc.nvim
term: tmux
platform: linux
```

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by LanHikari22** [comment]
Thank you for the pointer! I fixed the issue!

I traced it to this [issue] and fixed it by removing -Xbootclasspath... from
``` 
"java.jdt.ls.vmargs": "-javaagent:/usr/local/share/lombok/lombok-1.18.12.jar -Xbootclasspath/a:/usr/local/share/lombok/lombok-1.18.12.jar"
```
which I had to use to get lombok to be recognized.

[issue]: https://github.com/redhat-developer/vscode-java/issues/580
