### ISSUE TITLE
Generate getter + setter more intuitive control

### ISSUE THREAD

**Issue by jacksonludwig** [neoclide/coc-java#118]
I was confused as to actually generate getters/setters that I wanted with the associated code action. 

Currently it seems you can only escape out of the menu to confirm your selection, but I think it would make much more sense if there was an extra option added, something like "Confirm" to this list:
![image](https://user-images.githubusercontent.com/42984254/96348040-f2757700-1073-11eb-8497-6d8ee2e4a712.png)
or maybe that an empty selection confirms your previous selection and escape cancels instead of the way it is now.

Thanks a lot for this extension.

**Comment by Ec2coder** [comment]
How did you get those options to appear?

**Comment by bertin0** [comment]
> I was confused as to actually generate getters/setters that I wanted with the associated code action.
> 
> Currently it seems you can only escape out of the menu to confirm your selection, but I think it would make much more sense if there was an extra option added, something like "Confirm" to this list: ![image](https://user-images.githubusercontent.com/42984254/96348040-f2757700-1073-11eb-8497-6d8ee2e4a712.png) or maybe that an empty selection confirms your previous selection and escape cancels instead of the way it is now.
> 
> Thanks a lot for this extension.

Wow thanks so much for this info, until now I thought that it was just bugged and the only way to use these generators was to select all and then delete the unneeded ones afterwards. Indeed it is very unintuitive the way it works now.

> How did you get those options to appear?

If you use the config from the coc.nvim readme.md you will have a keybinding for code actions set as `<leaader>-c-a`

**Comment by chemzqm** [comment]
Should be fixed on recent version of coc-java, try upgrade coc.nvim to latest release and coc-java to version 1.14.0.

Multiple selection is support with latest coc-java and coc.nvim.
