### ISSUE TITLE
Error starting jdt language server downloaded by coc-java

### ISSUE THREAD

**Issue by bgx90** [neoclide/coc-java#12]
I am using nvim v0.3.4.  I have installed coc.nvim using nvim's builtin package manager and running `:call coc#util#install()` in nvim and the installation completed successfully.  Yarn was installed automatically during the installation, so I opened nvim in a new terminal to install coc-java.  When I ran `:CocInstall coc-java`. The installation stopped without installing coc-java and gave a message complaining that yarn was already installed and that I should remove it (I don't think that should have happened).  I removed yarn and reran `:CocInstall coc-java` which then succeeded and resulted in jdt ls being downloaded.  I closed nvim and ran `nvim hello.java` from the terminal to create a new java file to try out the plugin.  Nvim immediatley gave me this error message:

> [coc.nvim] JDT Language Server starting at /home/user/java
> [coc.nvim] Error output from java: Connection to server is erroring. Shutting down server.
> [coc.nvim] Error output from java: Connection to server is erroring. Shutting down server.
> [coc.nvim] Error output from java: Connection to server is erroring. Shutting down server.
> [vim-node-coc]: Uncaught exception: TypeError: Cannot convert object to primitive value
>     at ChildProcess.client_1.BaseLanguageClient.createMessageTransports.serverProcess.on.code (/snapshot/coc.nvim/lib/language-client/index.js:348:39)
>     at emitTwo (events.js:126:13)
>     at ChildProcess.emit (events.js:214:7)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)

I am just trying to create a single "hello world" java file; I am not creating a project of any kind.  I saw that someone had this error when trying to use their own separate jdt ls installation, but I am using the server installed by coc-java.  Have I missed something?

**Comment by chemzqm** [comment]
Run `:CocCommand java.updateLanguageServer` and wait for it finish, it could take some time.

Checkout `:h coc-status` for status line integration.

**Comment by bgx90** [comment]
When I run `:CocCommand java.updateLanguageServer` I get this message:
> [coc.nvim] Command 'java.updateLanguageServer' not found

I have verified that coc-java was installed and that the server was downloaded.  `:CocList extensions` lists coc-java.  I confirmed that I have the coc-java extension at `~/.config/coc/extensions/node_modules/coc-java/` and the jdt server files are in `~/.config/coc/extensions/coc-java-data/` (I am using Debian, config_linux is used)

> coc-java-data/
> └── server
>     ├── config_linux
>     │   └── config.ini
>     ├── config_mac
>     │   └── config.ini
>     ├── config_win
>     │   └── config.ini
>     ├── features
>     │   └── org.eclipse.equinox.executable_3.8.300.v20190213-1655.jar
>     └── plugins
>         ├── com.google.gson_2.7.0.v20170129-0911.jar
>         ├── com.google.guava_21.0.0.v20170206-1425.jar
>         ├── com.ibm.icu.base_58.2.0.v20170418-1837.jar
>         ├── javax.inject_1.0.0.v20091030.jar
>         ├── javax.xml_1.3.4.v201005080400.jar
>         ├── org.apache.ant_1.10.5.v20180808-0324.jar
>         ├── org.apache.commons.lang3_3.1.0.v201403281430.jar
>         ├── org.apache.log4j_1.2.15.v201012070815.jar
>         ├── org.eclipse.ant.core_3.5.300.v20190213-1305.jar
>         ├── org.eclipse.buildship.core_3.0.1.v20181217-1554.jar
>         ├── org.eclipse.compare.core_3.6.400.v20190214-2156.jar
>         ├── org.eclipse.core.commands_3.9.300.v20190215-1957.jar
>         ├── org.eclipse.core.contenttype_3.7.300.v20190215-2048.jar
>         ├── org.eclipse.core.expressions_3.6.300.v20190218-1215.jar
>         ├── org.eclipse.core.filebuffers_3.6.500.v20190218-1547.jar
>         ├── org.eclipse.core.filesystem_1.7.300.v20190218-2054.jar
>         ├── org.eclipse.core.jobs_3.10.300.v20190215-2048.jar
>         ├── org.eclipse.core.net_1.3.400.v20181030-1645.jar
>         ├── org.eclipse.core.net.linux.x86_64_1.2.300.v20181130-0925.jar
>         ├── org.eclipse.core.net.win32.x86_64_1.1.300.v20181126-0635.jar
>         ├── org.eclipse.core.resources_3.13.300.v20190218-2054.jar
>         ├── org.eclipse.core.runtime_3.15.200.v20190219-1009.jar
>         ├── org.eclipse.core.variables_3.4.400.v20190214-1545.jar
>         ├── org.eclipse.debug.core_3.13.200.v20190216-1557.jar
>         ├── org.eclipse.equinox.app_1.4.100.v20190215-2139.jar
>         ├── org.eclipse.equinox.common_3.10.300.v20190218-2100.jar
>         ├── org.eclipse.equinox.frameworkadmin_2.1.200.v20190215-2242.jar
>         ├── org.eclipse.equinox.frameworkadmin.equinox_1.1.100.v20180822-1258.jar
>         ├── org.eclipse.equinox.launcher_1.5.300.v20190213-1655.jar
>         ├── org.eclipse.equinox.launcher.cocoa.macosx.x86_64_1.1.1000.v20190125-2016.jar
>         ├── org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.1000.v20190125-2016.jar
>         ├── org.eclipse.equinox.launcher.win32.win32.x86_64_1.1.1000.v20190125-2016.jar
>         ├── org.eclipse.equinox.preferences_3.7.300.v20190218-2100.jar
>         ├── org.eclipse.equinox.registry_3.8.300.v20190218-2100.jar
>         ├── org.eclipse.equinox.security_1.3.100.v20190215-2139.jar
>         ├── org.eclipse.equinox.security.linux.x86_64_1.1.200.v20181106-0957.jar
>         ├── org.eclipse.equinox.security.macosx_1.101.100.v20180827-1235.jar
>         ├── org.eclipse.equinox.security.win32.x86_64_1.1.100.v20180827-1235.jar
>         ├── org.eclipse.equinox.simpleconfigurator_1.3.200.v20181101-1115.jar
>         ├── org.eclipse.equinox.simpleconfigurator.manipulator_2.1.200.v20181123-1405.jar
>         ├── org.eclipse.jdt.apt.core_3.6.300.v20190228-0624.jar
>         ├── org.eclipse.jdt.apt.pluggable.core_1.2.300.v20181206-1038.jar
>         ├── org.eclipse.jdt.compiler.apt_1.3.500.v20190218-0525.jar
>         ├── org.eclipse.jdt.compiler.tool_1.2.500.v20190218-0525.jar
>         ├── org.eclipse.jdt.core_3.17.0.v20190227-1706.jar
>         ├── org.eclipse.jdt.core.manipulation_1.11.100.v20190213-1309.jar
>         ├── org.eclipse.jdt.debug_3.12.200.v20190218-2230.jar
>         ├── org.eclipse.jdt.junit.core_3.10.200.v20181025-0713.jar
>         ├── org.eclipse.jdt.junit.runtime_3.4.900.v20181012-1045.jar
>         ├── org.eclipse.jdt.launching_3.13.0.v20190222-0937.jar
>         ├── org.eclipse.jdt.launching.macosx_3.4.200.v20180823-0805.jar
>         ├── org.eclipse.jdt.ls.core_0.36.0.201903182216.jar
>         ├── org.eclipse.lsp4j_0.6.0.v20181130-0903.jar
>         ├── org.eclipse.lsp4j.jsonrpc_0.6.0.v20181130-0903.jar
>         ├── org.eclipse.ltk.core.refactoring_3.10.0.v20190216-1303.jar
>         ├── org.eclipse.m2e.archetype.common_1.11.0.20190220-2117.jar
>         ├── org.eclipse.m2e.core_1.11.0.20190220-2119.jar
>         ├── org.eclipse.m2e.jdt_1.11.0.20190220-2119.jar
>         ├── org.eclipse.m2e.lifecyclemapping.defaults_1.11.0.20190220-2119.jar
>         ├── org.eclipse.m2e.maven.indexer_1.11.0.20190220-2117.jar
>         ├── org.eclipse.m2e.maven.runtime_1.11.0.20190220-2117.jar
>         ├── org.eclipse.m2e.maven.runtime.slf4j.simple_1.11.0.20190220-2117.jar
>         ├── org.eclipse.m2e.workspace.cli_0.3.1.jar
>         ├── org.eclipse.osgi_3.13.300.v20190218-1622.jar
>         ├── org.eclipse.osgi.compatibility.state_1.1.400.v20190208-1533.jar
>         ├── org.eclipse.osgi.services_3.8.0.v20190206-2147.jar
>         ├── org.eclipse.osgi.util_3.5.200.v20190115-2323.jar
>         ├── org.eclipse.text_3.8.100.v20190218-2126.jar
>         ├── org.eclipse.xtend.lib_2.17.0.v20190304-0518.jar
>         ├── org.eclipse.xtend.lib.macro_2.17.0.v20190304-0518.jar
>         ├── org.eclipse.xtext.xbase.lib_2.17.0.v20190304-0518.jar
>         ├── org.gradle.toolingapi_5.0.0.v20181217-1554.jar
>         ├── org.hamcrest.core_1.3.0.v20180420-1519.jar
>         ├── org.jboss.tools.maven.apt.core_1.5.2.201812241535.jar
>         ├── org.junit_4.12.0.v201504281640.jar
>         └── org.slf4j.api_1.7.2.v20121108-1250.jar

**Comment by adelarsq** [comment]
For me appears this error after to execute `CocCommand java.updateLanguageServer`:

```
[coc.nvim] Command error: connect ETIMEDOUT 198.41.30.199:80
```

**Comment by adelarsq** [comment]
@chemzqm `coc-java` is installed, but can't start on Java projects. Yesterday using the `java.jdt.ls.home` configuration. :thinking:

**Comment by bgx90** [comment]
I downloaded jdt-language-server-0.36.0-201903201910.tar.gz from the link given by @chemzqm.  I removed the existing jdt ls files from `~/.config/coc/extensions/coc-java-data/server/` and extracted the downloaded files to that directory.  I was able to successfully run `:CocCommand java.updateLanguageServer` after that.  When I try to open a java file, i see the message `jdt starting` in the status bar, but I still get the same error as before and the server never starts; the `jdt starting` keeps showing next to a spinning wheel in the status bar.

> [coc.nvim] JDT Language Server starting at /home/user/java
> [coc.nvim] Error output from java: Connection to server is erroring. Shutting down server.
> [coc.nvim] Error output from java: Connection to server is erroring. Shutting down server.
> [coc.nvim] Error output from java: Connection to server is erroring. Shutting down server.
> [vim-node-coc]: Uncaught exception: TypeError: Cannot convert object to primitive value
>     at ChildProcess.client_1.BaseLanguageClient.createMessageTransports.serverProcess.on.code (/snapshot/coc.nvim/lib/language-client/index.js:348:39)
>     at emitTwo (events.js:126:13)
>     at ChildProcess.emit (events.js:214:7)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)

**Comment by adelarsq** [comment]
@chemzqm I have confirmed that the `java.jdt.ls.home` isn't working. Following @bgx90 approach works.

**Comment by chemzqm** [comment]
Make sure there is a `.project` file in your project root.

**Comment by adelarsq** [comment]
@chemzqm It's there. I have downloaded the jls and extracted in the `~/.config/coc/extensions/coc-java-data/server/` folder so it works fine.

**Comment by chemzqm** [comment]
@adelarsq Fixed jdt.ls.home not work.

**Comment by bgx90** [comment]
> Make sure there is a `.project` file in your project root.

So, does this extension only work with eclipse projects and not just individual java files outside of a project?

**Comment by chemzqm** [comment]
@bgx90 No, then your have to make sure your vim's cwd is root of project, since it can't locate project root, vim's cwd is used.

**Comment by bgx90** [comment]
@chemzqm  I found the cause of my problem.  When I tried to start nvim from the command line with `nvim hello.java` to start nvim and create a buffer for a java file or run `:e hello.java` from inside nvim, the fact that only a buffer was created and not a file which seems to confuse the extension or the server which seem to only cope with files.   If I create a file with `touch hello.java` and then run `nvim hello.java` from the terminal or `:e hello.java` after starting nvim, the extension works.  So, the issue I was seeing was caused by the fact that the extension/server is working with files only and not vim buffers.  Thanks for your help.

**Comment by adelarsq** [comment]
It's working! Thanks @chemzqm

**Comment by rockneverdies55** [comment]
None of the above worked for me. What I did was to forcefully remove the content of coc-java folder.

So `rm -rf ~/.config/coc/extensions/coc-java-data/*` then launch `nvim` in my project root dir and open an arbitrary java file from the project. First coc.nvim displayed *jdt.ls not found it's being downloaded* message followed by *starting java language server* message and finally it started.

**Comment by L1szt** [comment]
@rockneverdies55 unfortunately still doesn't resolve the issue for me

**Comment by wt1024** [comment]
> @rockneverdies55 unfortunately still doesn't resolve the issue for me

me too..

**Comment by adelarsq** [comment]
@wt1024 maybe some breaking change since then. But I don't work with Java anymore (and coc) to be able to help on this :/
