### ISSUE TITLE
Cannot configure decompilers to work

### ISSUE THREAD

**Issue by jaghaimo** [neoclide/coc-java#122]
As per README, added `"java.contentProvider.preferred": "fernflower",`.

Went to linked repo (https://github.com/dgileadi/vscode-java-decompiler) and copied 4 jar files to `.config/coc/extensions/coc-java-data/server/plugins` (assumed this is the right location).

Whenever I try to check implementation, I end up with skeleton class:
```
 // Failed to get sources. Instead, stub sources have been generated by the disassembler.
 // Implementation of methods is unavailable.
```

What am I missing?

**Comment by jaghaimo** [comment]
Safe to close, as soon as posted decided to `CocInstall https://github.com/dgileadi/vscode-java-decompiler` and voila, all is good. Perhaps worth updating README.md to avoid such rookie mistakes...

**Comment by gagara** [comment]
@jaghaimo is there any way to open a standalone *.class file with this plugin?

**Comment by jaghaimo** [comment]
Sorry, I no longer work with Java. There were some standalone decompilers as far as I remember.
