### ISSUE TITLE
JavaFX package is not accessible for intellisense

### ISSUE THREAD

**Issue by joshpetit** [neoclide/coc-java#123]
In my Gradle (v6.7) project I am using the JavaFX plugin (v0.0.8). When I try and import the JavaFX package I receive a `The type javafx.packageName.className is not accessible` error. I am able to compile and run my program perfectly fine and have tried reinstalling coc-java.

### What I have tried
- I first suspected that it might just be because the language server couldn't detect JavaFX because I was using a Gradle plugin, so I added JavaFX as an implementation dependency in my build.Gradle, this did not fix anything
- I thought that it could possibly be because of the java version, I had difficulties getting Gradle to compile with JDK 14, so I set java.home to JDK 11 ( which corresponds to everything else).  This didn't help either

I am thinking that this is an issue with the language server possibly but I am not entirely sure what to think, any help? Here is my Coc info if that is useful:

## versions

vim version: VIM - Vi IMproved 8.1 8012269
node version: v10.19.0
coc.nvim version: 0.0.79-3e5fbe3a93
coc.nvim directory: /home/joshu/.vim/plugged/coc.nvim
term: dumb
platform: linux

## Log of coc.nvim

2020-11-03T08:27:12.607 INFO (pid:17819) [extensions] - Skipped load vim plugin from "/home/joshu/.config/coc/extensions/node_modules/coc-snippets", "coc-snippets" already global extension.
2020-11-03T08:27:12.732 INFO (pid:17819) [plugin] - coc.nvim 0.0.79-3e5fbe3a93 initialized with node: v10.19.0 after 136ms
2020-11-03T08:27:12.749 INFO (pid:17819) [services] - registered service "java"
2020-11-03T08:27:12.753 INFO (pid:17819) [language-client-index] - Language server "java" started with 17851

I'm also using v1.5.0 of coc-java

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by chemzqm** [comment]
Seems you need help from jdt.ls, not us.
