### ISSUE TITLE
<my-class>.java is a non-project file, only syntax errors are reported [Java: 16]

### ISSUE THREAD

**Issue by xebcan** [neoclide/coc-java#124]
Whenever I set a package declaration on a class file, I get a warning that says "[my-class].java is a non-project file, only syntax errors are reported [Java: 16]".
![image](https://user-images.githubusercontent.com/55932127/98284396-6fab5200-1f77-11eb-8cf9-9232a4cad7f5.png)
I searched the web for this error but didn't find anything, so, I started looking at the coc directory in .config and found out that there is a directory called ***coc-java-data*** under ***~/.config/coc/extensions/***
where apparently whenever a file with the .java extension is opened, coc or coc-java (I don't know which one) creates a directory with a name that starts with "jdt_ws_" followed by a very long number. Inside there is a directory that resembles a eclipse workspace with the following sub files and directories.
![image](https://user-images.githubusercontent.com/55932127/98287327-92d80080-1f7b-11eb-816a-d263ca5f1a27.png)
(for some reasone the directory ***bin/packageA*** contains a ***.class*** file with the name of the file that I'm having the problem but  ***src/packageA*** doesn't contain the ***.java*** file) and if I copy the ***.java*** file that gives the warning in the corresponding ***src/packageA*** directory, coc-java stops showing the warning there but it still shows it in the original file path, so, I was wondering how can I make coc-java not complain about this, without having to move every single file that Im working on to those directories created by coc-java or coc?

This only happens when I set a package name.

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by rustushki** [comment]
@xebcan - I had a problem with the same symptom just this week. For me, the solution was to use Java 11, setting environment variable JAVA_HOME to the Java 11 install path. Further, it looks like jdtls requires 11: https://github.com/eclipse/eclipse.jdt.ls#first-time-setup

**Comment by xebcan** [comment]
Thanks, I will try that.

**Comment by xebcan** [comment]
Yes. I can confirm that jdk11 and the latest jdt_ls fixes the problem.

**Comment by yangwuju** [comment]
"java.server.launchMode": "LightWeight"
