### ISSUE TITLE
Code Action to create file fails

### ISSUE THREAD

**Issue by ludwj61** [neoclide/coc-java#127]
When trying to generate a new interface that is not yet created, an error occurs and the file isn't produced.

For example:
![image](https://user-images.githubusercontent.com/42984254/99587977-ef91dd00-29b7-11eb-8e1a-485441102da1.png)

results in:
![image](https://user-images.githubusercontent.com/42984254/99588020-fcaecc00-29b7-11eb-9ee3-bcb900c897b9.png)

The error goes away when I make an empty ``Polynomial.java`` file.

This occurs with the latest version of the plugin and coc. I am on neovim nightly.

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.
