### ISSUE TITLE
Format style does not work

### ISSUE THREAD

**Issue by GiuseppeCesarano** [neoclide/coc-java#132]
This is basically a duplicate of #66. Specifying the path for the formatter does not apply the formatting rules, also, if a project has a .settings, the formatter rules are ignored. jdt.ls actully supports those features and they work as expected work on vscode

**Comment by nicobao** [comment]
It works, but you probably have different indentation rule in your .vimrc that messes up with the formatter file. Basically coc-java is made in a way that it is _changing_ the behaviour of the formatter file by sending it external options from your vim.

I think it is a terrible idea, and I tried to explained that to the maintainer of coc.nvim.
I suggested to make a PR to add a configurable option to disable that functionality: he refuses...

https://github.com/neoclide/coc-prettier/issues/1#issuecomment-721696534

**Comment by chemzqm** [comment]
Tabsize and expandtab retrives from buffer options shiftwidth and expandtab, that's how lsp works since coc.nvim have no knowledge of your format settings file.

**Comment by chemzqm** [comment]
You have to use plugins like vim-project or write vim script to ensure they're correct.

**Comment by nicobao** [comment]
Yea, but you can simply ignore those options and not send anything in "options". Or at least provide this as an option. coc.nvim does not need to know anything about the format settings file.

When you say, it's how "LSP works", it's not true as well. LSP provide a mean to send "options" but you don't _have_ to use it. It's just a protocol.

**Comment by chemzqm** [comment]
Those option have to be send to server according to the lsp doc.

**Comment by nicobao** [comment]
What is more important: the LSP doc, or the usefulness of the implemented behaviour? Is it working if you send blank options?

**Comment by chemzqm** [comment]
VSCode support workspace folder settings, you only need that for your buffer option.

**Comment by nicobao** [comment]
coc.nvim is targetting vim not VSCode - and it has much wider range of different usage than VSCode.
Again, simply check https://github.com/tpope/vim-sleuth

**Comment by chemzqm** [comment]
It might work but may also breaks other language server, I can make them optional if the doc says they could be missed,

**Comment by nicobao** [comment]
If you can make it optional but default is current behaviour, people could turn on that option when they want.
vim users are power users, they do things at their own risk.

**Comment by chemzqm** [comment]
I don't feel like that idea, but you can change the code and we could support format settings from workspace folder configuration of coc.nvim to override buffer settings, need to support language specfic configurations first.

**Comment by nicobao** [comment]
For info we got some implementation recommendations from the Microsoft team here: https://github.com/microsoft/language-server-protocol/issues/1166#issuecomment-957325352

**Comment by nicobao** [comment]
> Those option have to be send to server according to the lsp doc.

@chemzqm For info we got some implementation recommendations from the Microsoft team here: https://github.com/microsoft/language-server-protocol/issues/1166#issuecomment-957325352

Dirk recommends not to send data to the server if the values are unknown.

**Comment by chemzqm** [comment]
We don't know if vim's option is `unknown` or not, no such kind of api as far as I know.
My suggestion is change your buffer's option by read something like `.editorconfig` in your project or send feature request to language server for provide an option to ignore format option from client.
