### ISSUE TITLE
Uncaught exception: Header must provide a Content-Length property.

### ISSUE THREAD

**Issue by fidelski** [neoclide/coc-java#133]
When opening a Java file for editing I get the error:

`[coc.nvim]: Uncaught exception: Header must provide a Content-Length property.`

I only get this error when editing Java files, not with CPP files in conjunction with `coc.clangd`. As a result I get an infinite attempt of trying to start jdt what never succeeds.

Installed extensions:

* coc-snippets 2.2.10
* coc-java 1.5.3
* coc-cmake 0.0.3
* coc-clangd 0.6.0

Using nvim v0.4.4 or VIM 8.2 1-1897 on ubuntu 18

I have seen others report the same issue with different extensions but other than updating the corresponding extension I haven't found any suitable solution. I also don't know what exactly is causing it. Any help appreciated.

**Comment by chemzqm** [comment]
Should be issue with your jdt.ls, there's command to update it.

**Comment by fidelski** [comment]
I already tried this, with `CocCommand java.updateLanguageServer`, unfortunately it didn't help.

**Comment by fidelski** [comment]
Sorry for bothering, after a complete wipe of all vim plugins and all coc extensions, including a removal of all files within `.config/coc` and a reinstall of everything, the error is gone.

**Comment by JuanManuelRB** [comment]
I was able to solve this same problem by uninstalling `coc-java`, deleting the folder `~/.config/coc/extensions/coc-java-data/`, and reinstalling `coc-java` again

**Comment by ProgrammingLife** [comment]
> I was able to solve this same problem by uninstalling `coc-java`, deleting the folder `~/.config/coc/extensions/coc-java-data/`, and reinstalling `coc-java` again

Tried this with coc-omnisharp - it didn't work.

**Comment by m-GDEV** [comment]
I've had this issue repeatedly even with a newer version of both coc-nvim and coc-java and `:CocRestart` also seems to temporarily fix the issue.
