### ISSUE TITLE
list the requirement in the README (jdt 57 and java 11)

### ISSUE THREAD

**Issue by mirsella** [neoclide/coc-java#137]
from what i've seen for now this extension only work with java 11 and manually extracting jdt V57 into the coc-java-data/server directory.
i think it would be easier for new user to know what they need for this plugin to be working without having to search in the closed issue what version of java and the jdt they should manually install.
just a warning message, i'm not asking for a fix to this probably complicated problem.

thanks

**Comment by nicobao** [comment]
You don't need jdt v57. It works fine with the latest eclipse.jdt.ls version. See https://github.com/neoclide/coc-java/issues/139

**Comment by mirsella** [comment]
thanks for the reply, it's my bad.

when first installing i was with the same setup but didn't work.
i had java 11 installed but not set as default, and nothing would work but jdt 57 + java 11, i retried to clean install (delete plugged/coc-java and coc-java-data) and it doesn't crash so i guess it's fixed.

**Comment by nicobao** [comment]
> thanks for the reply, it's my bad.
> 
> when first installing i was with the same setup but didn't work.
> i had java 11 installed but not set as default, and nothing would work but jdt 57 + java 11, i retried to clean install (delete plugged/coc-java and coc-java-data) and it doesn't crash so i guess it's fixed.
> 
> sorry for the dumb issue

No worries, I am not a maintainer, nor a commiter, just a fellow user trying to help, just like you ;)
I do think documentation could be improved, as always with software. If you want, suggest a PR, maybe the maintainers will accept!...
