### ISSUE TITLE
java.updateLanguageServer download the wrong eclipse.jdt.ls version

### ISSUE THREAD

**Issue by nicobao** [neoclide/coc-java#139]
Try it locally, `java.updateLanguageServer` downloads `~/.config/coc/extensions/coc-java-data/server/jdt-language-server-0.9.0-201711302113.tar.gz` instead of  `~/.config/coc/extensions/coc-java-data/server/jdt-language-server-latest.tar.gz` which currently corresponds to `jdt-language-server-0.68.0-202012242230.tar.gz`. Version 0.9 was probably an error from Eclipse. It is annoying because it renders `java.updateLanguageServer` unusable. Besides version 0.9.0 leads to `Uncaught exception: Header must provide a Content-Length property`.

**Comment by nicobao** [comment]
Okay, now it works, and it is logical from the source code:

https://github.com/neoclide/coc-java/blob/master/src/downloader.ts#L25

I don't understand why, it was downloading the wrong version of Eclipse.jdt.ls. I cannot reproduce the issue.

**Comment by nicobao** [comment]
From previous command, maybe there is a bug when trying to download the newest server and the content of `~/.config/coc/extensions/coc-java-data/server/` contains already a specific version?...

**Comment by nicobao** [comment]
I consistently reproduce this bug every time I use the command.

**Comment by chemzqm** [comment]
Should be fixed on recent version of coc-java, try upgrade coc.nvim to latest release and coc-java to version 1.14.0.

From 1.14.0, coc-java used bundled jdt.ls instead.
