### ISSUE TITLE
Format ignores (indent) settings.

### ISSUE THREAD

**Issue by BonaBeavis** [neoclide/coc-java#14]
### Situation
Indent is set in `org.eclipse.jdt.core.prefs` to 4.
Indent is set in init.vim to 4
```vim
setl shiftwidth=4
setl tabstop=4
```
Formatting with Eclipse gives an indent of 4.
Formatting with vim-lsp gave an indent of 4.

### Problem
When formatting with coc-java indent is set to 2.

**Comment by chemzqm** [comment]
Please paster verbose output from language server https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by BonaBeavis** [comment]
This should be the relevant section:
```json
[Trace - 17:27:44] Sending request 'textDocument/hover - (31)'.
Params: {
    "textDocument": {
        "uri": "file:///home/beavis/cloud/repositories/apache-nifi-rdf/processors/nifi-sparql-integrate-bundle/nifi-sparql-integrate-processors/src/main/java/org/aksw/sparql_integrate/processors/sparql_integrate/SparqlIntegrateProcessor.java"
    },
    "position": {
        "line": 254,
        "character": 21
    }
}


[Trace - 17:27:44] Received response 'textDocument/hover - (31)' in 13ms.
Result: {
    "contents": [
        {
            "language": "java",
            "value": "void org.apache.jena.sparql.core.Transactional.begin(ReadWrite readWrite)"
        },
        "Start either a READ or WRITE transaction.\n\n *  **Parameters:**\n    \n     *  readWrite"
    ]
}
```

**Comment by chemzqm** [comment]
It's not, it's doHover request.

**Comment by BonaBeavis** [comment]
I run the command `:call CocActionAsync('doHover')`, but a grep for 'dohover' in the output from lsp returns nothing.

[l.log](https://github.com/neoclide/coc-java/files/3023740/l.log)
## versions

vim version: NVIM v0.4.0-dev
node version: v8.9.0
coc.nvim version: 0.0.63
term: xterm-256color
platform: linux

**Comment by BonaBeavis** [comment]
Sorry, wrong Issue.

But here is the log: 
[form.log](https://github.com/neoclide/coc-java/files/3023775/form.log)

**Comment by BonaBeavis** [comment]
https://github.com/Microsoft/vscode/issues/10339

**Comment by chemzqm** [comment]
Fixed on master of coc.nvim.
