### ISSUE TITLE
Attach source code manually

### ISSUE THREAD

**Issue by hsnotebook** [neoclide/coc-java#140]
I have org.apache.hadoop:hadoop-client:2.8.5 in my pom.xml, and when I go to definition of a class in that jar file, show me this:

>  // Failed to get sources. Instead, stub sources have been generated by the disassembler.
>  // Implementation of methods is unavailable.

I have downloaded the source, but how can I attach it?

**Comment by chemzqm** [comment]
You have to seek help from jdt.ls.
