### ISSUE TITLE
Question about coc-java-data

### ISSUE THREAD

**Issue by TomSchammo** [neoclide/coc-java#141]
I have a question about the coc-java-data folder in `~/.config/coc/extensions/coc-java-data`. In one of the subfolders I found some files and I wanted to ask what they are for/why they are there in general.

Some of source files I probably opened at some point, others are mp4 video files that in a couple of folders back in the file hirarchy.

Why are those files copied to said location, what it is used for?

**Comment by chemzqm** [comment]
They're jdt.ls, you can clean them up.

**Comment by TomSchammo** [comment]
Thanks!
