### ISSUE TITLE
Organize import line endings when 'fileformat'=dos

### ISSUE THREAD

**Issue by rustushki** [neoclide/coc-java#143]
**Summary**
When organizing imports, an extraneous \r is appended to the end of each inserted import statement line. This only occurs when 'fileformat' is set to dos. I've been able to reproduce the issue on Ubuntu Linux and Windows 10. I'm uncertain whether this is a problem with coc-java, coc.nvim, or jdtls.

**Steps to Reproduce**
1. Open nvim + coc.nvim with coc-java installed
2. Open a Java source file with some import statements
3. Rearrange or remove some import statements
4. If not already, set the fileformat to dos and save (i.e. :set ff=dos)
5. Run: :CocCommand java.action.organizeImports
6. Observe that each inserted or rearranged import statement ends with a "^M" character

The response from the language server is different when the line endings are dos or unix. If dos:

```
Result: {
    "changes": {
        "<snip>.java": [
            {
                "range": {
                    "start": {
                        "line": 2,
                        "character": 0
                    },
                    "end": {
                        "line": 2,
                        "character": 0
                    }
                },
                "newText": "import java.lang.reflect.Constructor;\r\nimport java.lang.reflect.InvocationTargetException;\r\nimport java.util.List;\r\n\r\n"
            }
        ]
    }
}

```

If unix:
```
Result: {
    "changes": {
        "<snip>.java": [
            {
                "range": {
                    "start": {
                        "line": 2,
                        "character": 0
                    },
                    "end": {
                        "line": 2,
                        "character": 0
                    }
                },
                "newText": "import java.lang.reflect.Constructor;\nimport java.lang.reflect.InvocationTargetException;\nimport java.util.List;\n\n"
            }
        ]
    }
}

```

coc.nvim: 0.0.80
coc-java: 1.5.3

**Comment by chemzqm** [comment]
It's added by your vim

**Comment by rustushki** [comment]
Both nvim 0.5.0 (g02a3c479) and vim 8.2 show this behavior of inserting ^M. It can be observed when running this command: :call :setline(".", "something\r")

I think three things are in play:
1. The language server now supports '\r\n' line endings (at least when organizing imports)
2. coc-java is splitting the newText from the language server response by '\n', leaving a '\r' on each line
3. vim's setline() function does not allow the insertion of blank lines by including newline characters

No. 1 happened sometime in the last couple of months.

I'm working around this problem by setting ff=unix when possible. Otherwise, I'm running :%s/\r//g after performing an organize imports.
