### ISSUE TITLE
Package is, but show coc error

### ISSUE THREAD

**Issue by kert-daiki** [neoclide/coc-java#144]
Hello, 

coc show me this: 
![Screenshot 2021-02-16 165855](https://user-images.githubusercontent.com/64678724/108127053-a6b1f900-7078-11eb-8690-a73c5d9ab962.png)
but when i compile it, don't show any error, and create a normal package

any can help me?

thank you

my system is windows 10
java version
![java-version](https://user-images.githubusercontent.com/64678724/108127258-001a2800-7079-11eb-8269-f4bc64bac7d0.png)
neovim version
![nvim-version](https://user-images.githubusercontent.com/64678724/108127289-07413600-7079-11eb-97af-35591e8beb7f.png)

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
