### ISSUE TITLE
Question about editor.action.organizeImport

### ISSUE THREAD

**Issue by cheonhyangzhang** [neoclide/coc-java#147]
Hi 
in some codebase, it is acceptable to use * in the import.
```
import static org.mockito.Mockito.*;
```
whenever run editor.action.organizeImport command, it will replace with 
```
     5 import static org.mockito.Mockito.only;
     6 import static org.mockito.Mockito.verify;
     7 import static org.mockito.Mockito.when;
```

is it possible to config coc-java to not replace the * import?

**Comment by dansomething** [comment]
Have you tried setting `java.sources.organizeImports.staticStarThreshold`? I believe it defaults to 99.

**Comment by cheonhyangzhang** [comment]
thanks, 
tried using `java.sources.organizeImports.staticStarThreshold` and it works! 
thanks !
