### ISSUE TITLE
Cannot go to declaration (coc-declaration)

### ISSUE THREAD

**Issue by ousatov-ua** [neoclide/coc-java#153]
Hi!
I'm using coc-java.
coc haș possibility to go to declaration, but when I try to use it I have next:

>[coc.nvim]: Error on notification "jumpDeclaration": declaration provider not found for current buffer, your language server don't support it.

I know about ctags... but will it be implemented in con-java?
Maybe it is no available in LS.. don't know.

Thanks.

**Comment by uestueab** [comment]
What a bullshit project holy fuck. Op raised an issue in april.20 still no answer. If you guys would only take documenting as seriously as coding a lot of our free times would be spared

**Comment by chemzqm** [comment]
>  your language server don't support it.

Is that not clear?

**Comment by guest73** [comment]
> > your language server don't support it.
> 
> Is that not clear?

Not clear. It has to be "...doesn't support..."  :)
