### ISSUE TITLE
coc-java not allow to finish downloading jdtls

### ISSUE THREAD

**Issue by ayoubelmhamdi** [neoclide/coc-java#155]
this error bellow i perhaps is caused by slow connection
```
[coc.nvim] The "java" server crashed 5 times in the last 3 minutes. The server will not be restarted.
```
can you add some condition for testing if error from incomplete download or other reason 
because siteweb of original jdtls by eclipse very slow for me  
[http://download.eclipse.org/jdtls/snapshots/jdt-language-server-latest.tar.gz](http://download.eclipse.org/jdtls/snapshots/jdt-language-server-latest.tar.gz)

**Comment by chemzqm** [comment]
Try manually download jdt.ls https://github.com/neoclide/coc-java/blob/master/Readme.md#L7
