### ISSUE TITLE
How to ganerate serialVersionUID?

### ISSUE THREAD

**Issue by Geek-Zft** [neoclide/coc-java#159]
I have a class that implements Serializable interface, but how can i generate a serialVersionUID?

**Comment by chemzqm** [comment]
Can't understand.

**Comment by arleyvelascoo** [comment]
when i implement from Serializable i need the serialversionUID field in java, Can i generate this with coc?

**Comment by chemzqm** [comment]
Should be fixed on recent version of coc-java, try upgrade coc.nvim to latest release and coc-java to version 1.14.0.

The action is provided by jdt.ls https://github.com/eclipse/eclipse.jdt.ls/pull/514
