### ISSUE TITLE
Reinstall coc-java including jdt?

### ISSUE THREAD

**Issue by sflomenb** [neoclide/coc-java#16]
I’m experiencing some errors from jdt after using the CocCommand to download the latest. I’d like to uninstall Coc-java along with the jdt language server, and then reinstall it all. I used CocUninstall but that doesn’t seem to have uninstalled jdt. What would you recommend here? Is there a supported way to uninstall jdt as well? Where does it get installed to? Thanks!

**Comment by chemzqm** [comment]
You can download complied jdt.ls at https://download.eclipse.org/jdtls/snapshots/?d and set `"java.jdt.ls.home"` to the extracted folder.
