### ISSUE TITLE
Is there possibility to re-use JDT LS server started by another vim/nvim instance?

### ISSUE THREAD

**Issue by ousatov-ua** [neoclide/coc-java#161]
Hi!
Thank you for the plugin! :)

I'm wondering if there is a possibility to re-use JDT LS instance already started by previous vim/nvim process?
Right now every new instance of vim/nvim will start its separate JDT LS server - maybe it is simple to check if JDT LS already running and re-use it?

Thank you in advance :)

**Comment by chemzqm** [comment]
It's not possible yet.

**Comment by chemzqm** [comment]
It's not possible yet.

**Comment by ousatov-ua** [comment]
I see, thanks!
Sorry, do you plan to add this feature? :)

**Comment by chemzqm** [comment]
No, unless there's standard protocol defined by LSP.

**Comment by ousatov-ua** [comment]
I see, thanks.

**Comment by chemzqm** [comment]
You may want to use share indexes support provided by coc-java@1.14.0.
