### ISSUE TITLE
is it possible to use CLASSPATH variable ?

### ISSUE THREAD

**Issue by Hax4us** [neoclide/coc-java#162]
i was using ale + javalsp where `CLASSPATH` variable was honoured. but here not. Yes i know i can set external libs using `coc-settings.json` but i want to use CLASSPATH.

**Comment by JartX** [comment]
@Hax4us 
+1 i also need it to android development: https://github.com/hsanson/vim-android

**Comment by MuhammadSawalhy** [comment]
Any progress here?

**Comment by chemzqm** [comment]
Don't know, that author is incapacitated for this.

**Comment by MuhammadSawalhy** [comment]
> Don't know, the author is incapacitated for this.

Ok @chemzqm, we can deal with this issue for now with some workarounds as some people did in this issue: https://github.com/neoclide/coc-java/issues/93

I think this is something related to the language server **jdtls** itself, not **coc-java**. Some issues are open there in **jdtls** repo such as https://github.com/eclipse/eclipse.jdt.ls/issues/1986.

**Comment by chemzqm** [comment]
Use configuration `java.project.referencedLibraries` instead, which support workspace folder configuration.
