### ISSUE TITLE
"Move class" refactoring

### ISSUE THREAD

**Issue by ranyadshalom** [neoclide/coc-java#169]
It seems like the language server supports it (e.g. see [this](https://github.com/eclipse/eclipse.jdt.ls/pull/1529)), but I don't see it in my code actions menu. Is this a bug, or is this not yet supported by coc-java?

**Comment by chemzqm** [comment]
Should be fixed on recent version of coc-java, try upgrade coc.nvim to latest release and coc-java to version 1.14.0.
