### ISSUE TITLE
Javadoc is not displayed when calling CocAction('doHover')

### ISSUE THREAD

**Issue by bgx90** [neoclide/coc-java#17]
I am using OpenJDK 11 on Debian and have the corresponding doc package installed.  Previously, I was getting javadoc info from the OpenJDK doc package when calling CocAction('doHover').  Now when I call `CocAction('doHover')` (using a keymapping or the command prompt) with the cursor on a keyword like `String`, I do not get the javadoc info from the doc package in the preview window like I did before.  Instead I get this:
![image](https://user-images.githubusercontent.com/7351168/55675103-25398f00-5883-11e9-8470-456076818e90.png)

This is the information I was seeing before I installed the doc package.

I don't know if it's related, but I started having this problem after I applied the fix for #15.  Before that, I was getting the correct documentation.

I updated the server from `jdt-language-server-0.36.0-201903201910` to `jdt-language-server-0.36.1-201904020132` by running `:CocCommand java.updateLanguageServer` to see if that would fix the issue, but it did not. 

This is the trace I get when i try to get the hover info:
```
[Trace - 3:45:08 PM] Sending request 'textDocument/hover - (5)'.
Params: {
    "textDocument": {
        "uri": "file:///home/user/udemy/maven/mb2g-lombok/src/main/java/guru/springframework/model/User.java"
    },
    "position": {
        "line": 12,
        "character": 14
    }
}


[Trace - 3:45:08 PM] Received response 'textDocument/hover - (5)' in 56ms.
Result: {
    "contents": {
        "language": "java",
        "value": "java.lang.String"
    }
}
```

**Comment by chemzqm** [comment]
It's expected, it's normal that server only return type for `doHover`.
You can use older verion of jdt.ls https://github.com/neoclide/coc-java/issues/16#issuecomment-479869258

**Comment by bgx90** [comment]
The odd thing is `doHover` was showing jdk javadocs before when I was using `jdt-language-server-0.36.0-201903201910` and it just seemed to stop after I pulled and the latest for coc.nvim to address #15 even though I was still using `jdt-language-server-0.36.0-201903201910`.  The update to coc.nvim was the only thing that changed (unless coc-java was automatically updated as well at some point).

I used `String` as an example, but the problem happens when trying to hover on methods as well:
```
[Trace - 6:16:29 PM] Sending request 'textDocument/hover - (20)'.
Params: {
    "textDocument": {
        "uri": "file:///home/user/udemy/maven/mb2g-lombok/src/main/java/guru/springframework/model/User.java"
    },
    "position": {
        "line": 16,
        "character": 17
    }
}


[Trace - 6:16:29 PM] Received response 'textDocument/hover - (20)' in 14ms.
Result: {
    "contents": {
        "language": "java",
        "value": "int java.lang.String.length()"
    }
}
```

This output is not very useful without the javadoc. Since `doHover` was returning javadoc before and the jdt.ls is meant to function like the jdt in eclipse, I think something is going wrong somewhere. It might be the server, but it seems strange that the server installation that was sending the javadoc would suddenly stop sending it.

However, if I add javadoc comments to my own code, they are displayed in the preview window as one would expect.
![image](https://user-images.githubusercontent.com/7351168/55676393-4659aa00-589a-11e9-9ce6-61af978b6a9c.png)
```
[Trace - 6:30:59 PM] Sending request 'textDocument/hover - (37)'.
Params: {
    "textDocument": {
        "uri": "file:///home/user/udemy/maven/mb2g-lombok/src/main/java/guru/springframework/model/User.java"
    },
    "position": {
        "line": 19,
        "character": 8
    }
}


[Trace - 6:30:59 PM] Received response 'textDocument/hover - (37)' in 14ms.
Result: {
    "contents": [
        {
            "language": "java",
            "value": "String firstName"
        },
        "This is my javadoc"
    ]
}
```

**Comment by chemzqm** [comment]
Don't know why jdt.ls stop sending javadoc from jdk for you and it works for me.

<img width="759" alt="Screen Shot 2019-04-07 at 8 41 44 AM" src="https://user-images.githubusercontent.com/251450/55676939-041f7f80-5911-11e9-809a-373da91d7d97.png">

**Comment by bgx90** [comment]
I found the issue.  I had set the `JAVA_HOME` environment variable to `/usr/lib/jvm/java-11-openjdk-amd64` for maven.  According to [this](https://github.com/eclipse/eclipse.jdt.ls/issues/620#issuecomment-380647352), the `JAVA_HOME` environment variable also determines the JVM used to run jdt.ls.  Apparently the path I set is preventing it from picking up the documentation.  After I unset `JAVA_HOME` and let jdt.ls detect the Java installation on its own, the jdk javadocs are displayed with `doHover` again.  Now I need to figure out how to set `JAVA_HOME` to something that will make maven and jdt.ls happy.

**Comment by chemzqm** [comment]
There is setting for that https://github.com/neoclide/coc-java#setting-the-jdk

**Comment by bgx90** [comment]
Is there a way to get coc to show the path it is currently using for the JDK so that I can put it in the setting?

**Comment by chemzqm** [comment]
I've added a message on extension activate.

**Comment by bgx90** [comment]
Okay, I've got it working now.  The odd thing is that when I unset the `JAVA_HOME` environment variable and checked the jdk path in the extension's activation message, it said that it was using `/usr/lib/jvm/java-11-openjdk-amd64` which is what I had the `JAVA_HOME` environment variable set to.  However, setting the `JAVA_HOME` environment variable alone still breaks the display of javadoc even though the activation message states that it is using the same path as it was without setting `JAVA_HOME`. It seems that something odd is happening when the extension sets the jdk path from the environment variable.  Adding `"java.home": "/usr/lib/jvm/java-11-openjdk-amd64"` to `coc-settings.json` does allow me to have javadoc display on `doHover` and keep the `JAVA_HOME` environment variable set for maven.

**Comment by bgx90** [comment]
After updating coc.nvim and coc-java, I am once again not getting javadoc from the language server.  Javadoc was working with `jdt-language-server-0.36.1-201904020132` after I made the changes to my settings described in [my last post](https://github.com/neoclide/coc-java/issues/17#issuecomment-480553576), so it seems that pulling and building the latest changes to coc has caused javadoc to stop getting displayed. I have tried unsetting the `JAVA_HOME` environment variable again since that seemed to be the cause of the problem before, but that did not work this time. I tried removing the `java.home` setting from `coc-settings.json` as well, but that has no effect either.  I have also manually updated jdt.ls to the latest snapshot (`jdt-language-server-0.37.0-201904162228`) and tried setting and unsetting `JAVA_HOME` and `java.home`, but I still cannot get javadoc to display in the preview window.

**Comment by bgx90** [comment]
This issue appears to be caused by `jdt.ls`.  I tried installing `vim-lps` and it does not get javadoc back from the server either.  This seems to be an intermittent bug, because I was getting javadoc on hover without any problems and then it just stopped working even though I had changed the version of the server I was using or any configuration related to it.

**Comment by ioperations** [comment]
solved by 
```bash
 sudo apt install openjdk-${VERSION}-source 
```

**Comment by rajitbanerjee** [comment]
I had a similar issue with no hover showing at all until I added this to my vimrc:
```
function! ShowDocIfNoDiagnostic(timer_id)
  if (coc#float#has_float() == 0 && CocHasProvider('hover') == 1)
    silent call CocActionAsync('doHover')
  endif
endfunction

function! s:show_hover_doc()
  call timer_start(500, 'ShowDocIfNoDiagnostic')
endfunction

autocmd CursorHoldI * :call <SID>show_hover_doc()
autocmd CursorHold * :call <SID>show_hover_doc()
```
Thanks to https://thoughtbot.com/blog/modern-typescript-and-react-development-in-vim#tool-tip-documentation-and-diagnostics
