### ISSUE TITLE
can not toggle service with CocAction

### ISSUE THREAD

**Issue by renzhamin** [neoclide/coc-java#170]
`CocAction('toggleService','java')` is not working

neither can I toggle by `CocList services` and press enter to toggle the service like all the other ones

I know i can still turn it off/on using coc#config but thats not toggling and toggleService really helps to generalize for all language servers

**Comment by chemzqm** [comment]
Should be fixed on recent version of coc-java, try upgrade coc.nvim to latest release and coc-java to version 1.14.0.
