### ISSUE TITLE
JavaSE-16/17 Support like vscode-java

### ISSUE THREAD

**Issue by UltiRequiem** [neoclide/coc-java#171]
How can I configure this extension to work openjdk 16.0.2 or newer?

**Comment by UltiRequiem** [comment]
VSCode Java Supports Java 16:
![image](https://user-images.githubusercontent.com/71897736/129372012-a272dc30-987c-4cd8-825b-6cb42abf7aa9.png)

https://github.com/redhat-developer/vscode-java#project-jdks

**Comment by juanvaldera** [comment]
+1

**Comment by sachasi** [comment]
+1

**Comment by wenhao-eb** [comment]
Would like to see something update on this issue.

**Comment by nextuponstream** [comment]
bump, tried with 17 but does not work

**Comment by kands-code** [comment]
![图片](https://user-images.githubusercontent.com/59006329/141606682-18f1f20a-1b84-48d2-9f09-abf3cea3254c.png)

Hope to support 17

**Comment by UltiRequiem** [comment]
> ![图片](https://user-images.githubusercontent.com/59006329/141606682-18f1f20a-1b84-48d2-9f09-abf3cea3254c.png)
> 
> Hope to support 17

Waiting for this since last year...

**Comment by SirWrexes** [comment]
I have this in my `~/.config/nvim/coc-settings.json` and no error.
Are you guys sure you have the latest versions of your stuff ?
```json
  "java.configuration.runtimes": [
    {
      "name": "JavaSE-17",
      "path": "/usr/lib/jvm/java-17-openjdk",
      "default": true
    }
  ]
```

**Comment by chemzqm** [comment]
Should be fixed on recent version of coc-java, try upgrade coc.nvim to latest release and coc-java to version 1.14.0.

**Comment by UltiRequiem** [comment]
Thanks!
