### ISSUE TITLE
java.workspace.compile doesn't work

### ISSUE THREAD

**Issue by lidulibai** [neoclide/coc-java#172]
When execute :CocCommand java.workspace.compile, then choose any compile type will got the same error message 'Error on "runComand': Message could not be parsed.

Here is the log:
[Trace - 3:02:07 PM] Sending request 'java/buildWorkspace - (3)'.
Params: [
    false
]

[Trace - 3:02:07 PM] Received response 'java/buildWorkspace - (3)' in 2ms. Request failed: Message could not be parsed. (-32700).
Error data: {
    "message": "java.lang.IllegalStateException: Expected a boolean but was BEGIN_ARRAY at line 1 column 66 path $.params"
}

**Comment by chemzqm** [comment]
It's expected request, try upgrade your coc.nvim and jdt.ls.

**Comment by lidulibai** [comment]
It works. Thanks a lot!
