### ISSUE TITLE
Go to definition for protos

### ISSUE THREAD

**Issue by nakulj** [neoclide/coc-java#173]
It would be great if there was some way to directly jump to the source proto file when hovering under a symbol generated from a proto.

This could be done by 'post processing' the code location returned by the language server. Generated proto classes usually have this comment at the top:

```java
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: foo.proto
```

It shouldn't be too hard to take a symbol like `Foo.barBaz`, transform it into the proto name `Foo.bar_baz`, and then look for it in the file pointed to by the comment.

Is coc-java the right place for this, or should this go in a different layer of the stack? If I wanted to write a PR for this functionality, where would I start?

**Comment by chemzqm** [comment]
Need support by language server

**Comment by chemzqm** [comment]
Use command `:CocList -I --input=Foo.bar_baz  symbols` to search symbols.
