### ISSUE TITLE
Is it possible to avoid modifying .settings/org.eclipse.jdt.core.prefs

### ISSUE THREAD

**Issue by cutefish** [neoclide/coc-java#174]
I find it that the entry org.eclipse.jdt.core.compiler.release in .settings/org.eclipse.jdt.core.prefs is always modified to disabled. In our repo, some other ecplise user sets it to other values. Is there a way for me to specify not setting this value? Thanks a lot.

**Comment by chemzqm** [comment]
Seems modified by jdt.ls, don't know if there's settings for that.

**Comment by chemzqm** [comment]
Should be fixed on recent version of coc-java, try upgrade coc.nvim to latest release and coc-java to version 1.14.0.

`"java.import.generatesMetadataFilesAtProjectRoot"` is `false` by default
