### ISSUE TITLE
Can't start server!!!

### ISSUE THREAD

**Issue by Fatpandac** [neoclide/coc-java#175]
OS       : windows 11
java se : 11.0.12
jdt.ls    : 1.3
[coc.nvim] The "java" server crashed 4 times in the last 3 minutes. The server will not be restarted.
![image](https://user-images.githubusercontent.com/30423976/133258650-930de515-7c49-4950-bd92-5cb0c2c40331.png)
![image](https://user-images.githubusercontent.com/30423976/133258758-3502bb84-b712-4787-9d19-9cd410e4e07d.png)

**Comment by kaiyulee** [comment]
@Fatpandac
Duplicate of #99

**Comment by Fatpandac** [comment]
I try on Debian with openjdk11, it's fine, but in Windows11, it's an error.

**Comment by Fatpandac** [comment]
It’s fine when I change my user file in English.
