### ISSUE TITLE
Unable to provide input to prompt

### ISSUE THREAD

**Issue by gautham18113** [neoclide/coc-java#176]
Hello!
Very silly question, does anyone know how to provide input to the yes or no prompt that shows up when the `:CocCommand java.clean.workspace` command is called? 
I have tried hitting 'y' multiple times, clicking on the prompt and entering ':y', nothing seems to work :(

<img width="1307" alt="Screen Shot 2021-09-20 at 12 13 12 PM" src="https://user-images.githubusercontent.com/26587110/134062943-b5bb93c9-05e8-4bd7-a60f-331e386a84db.png">

**Comment by chemzqm** [comment]
Press `y` or `n`, action list is provided from coc-java@1.14.0
