### ISSUE TITLE
How to add library javadoc?

### ISSUE THREAD

**Issue by xebcam** [neoclide/coc-java#178]
I can't figure out how to add javafx javadoc to get documentation when pressing (shift + k). I tried adding a path to the doc in .classpath but didn’t work, when pressing (shift + k) no documentation is shown. I also tried [this](http://eclim.org/vim/java/javadoc.html) but It didn't work either.

I downloaded the doc from [here](https://gluonhq.com/products/javafx/)

By the way. From where is coc-java getting the java javadoc? that works normal.

**Comment by chemzqm** [comment]
Should be fixed on recent version of coc-java, try upgrade coc.nvim to latest release and coc-java to version 1.14.0.
