### ISSUE TITLE
[coc-java] - Connection to server got closed. Server will not be restarted.

### ISSUE THREAD

**Issue by abdellatif-dev** [neoclide/coc-java#179]
nvim: v0.6.0-dev+327-gec447b879
distro: arch linux 

i installed jdt.ls but i keep getting this
error message: [coc-java] - Connection to server got closed. Server will not be restarted.

**Comment by MuhammadSawalhy** [comment]
I think you have the same issue as me which is a result of an old version of `jdtls`. So you have to download it yourself and put it in the right position or configure your custom `jstls` home directory as stated in the README of this repo. 

In my case it should be here: `~/.config/coc/extensions/coc-java-data/server`

Or extract the content of `jdtls` in a custom dir then set `"java.jdt.ls.home": "/your/custom/jstls/dir"` in `coc-config.js` or run this vim command to reach the coc configurations, `:CocConfig`.

**Comment by abdellatif-dev** [comment]
i switched to nvim-lsp
