### ISSUE TITLE
(documentation) explain how to customize compiler warnings

### ISSUE THREAD

**Issue by JulioJu** [neoclide/coc-java#18]
Hi,

Maybe it could be cool to add in the README.md a short paragraph that explain how to customize compiler warnings / errors.

It's a server side LSP customization, but for newbies it could be very very cool to have this documentation in the README.md of the current project.

Simply say that   we should add customization under `root_project/.settings/org.eclipse.jdt.core.prefs`  with values presented at https://help.eclipse.org/neon/topic/org.eclipse.jdt.doc.isv/reference/api/org/eclipse/jdt/core/JavaCore.html ?

Thanks in advance !

**Comment by jerrywang1981** [comment]
If there is wiki or readme on how to use this, it will help a lot. I want to know:
* How to start 
* How to debug

for now, I open terminal and run like
```
man spring-boot:run
```
but no idea of how to debug it.

**Comment by chemzqm** [comment]
PR welcome.

**Comment by chemzqm** [comment]
Added
