### ISSUE TITLE
Communicate to user once files have been recompiled

### ISSUE THREAD

**Issue by Philogy** [neoclide/coc-java#180]
It's a bit frustrating not knowing when new changes have been recompiled. Some sort of message in vim after a newly written .java file has been successfully compiled would be much appreciated! Somewhere in the bottom right for example or as a vim message.

**Comment by chemzqm** [comment]
Should be fixed on recent version of coc-java, try upgrade coc.nvim to latest release and coc-java to version 1.14.0.

Enabled status line support of coc.nvim `:h coc-status` or use command `:CocCommand java.show.server.task.status` to get task status.
