### ISSUE TITLE
Autocomplete repeat words bug | Linux, Neovim, AUR version

### ISSUE THREAD

**Issue by Nojipiz** [neoclide/coc-java#181]
My coc-java is doing weird autocomplete, only for specific keywords like _sysout_ or _fore_ 

Where _sysout_ autocomplete to "SSystem.out.print" and _fore_ autocomplete to "forfor(...)".

Here is a little demo, is it a bug? may be a config file? 

https://youtu.be/_AzMH2S6ErE

Thanks

**Comment by fannheyward** [comment]
Similar issue https://github.com/neoclide/coc.nvim/pull/3415

**Comment by Nojipiz** [comment]
@fannheyward  oh thanks, i will check

**Comment by codebysandwich** [comment]
@Nojipiz This question confused me too, how did you fix this?

**Comment by Nojipiz** [comment]
> @Nojipiz This question confused me too, how did you fix this?

Switching to the native lsp

**Comment by codebysandwich** [comment]
> > @Nojipiz This question confused me too, how did you fix this?
> 
> Switching to the built-in lsp

Thanks :)
