### ISSUE TITLE
Can't find definition in generated-sources like vscode

### ISSUE THREAD

**Issue by blithefeng** [neoclide/coc-java#185]
I have a big maven project, and there are five modules in it. In my project, one module named "common" is required by the other modules.
In "common" module, I have to compile the rpc code and use these codes in other modules. But when using eclipse.jdt.ls in neovim, I couldn't find the definition of the Variable defined in generated-sources. I got response like:

```java
// Failed to get sources. Instead, stub sources have been generated by the disassembler.
 // Implementation of methods is unavailable.
package my.proto;
```

But in vscode, I can jump to definition in generated-sources after compiled the dependent module.

**Comment by chemzqm** [comment]
Should be fixed on recent version of coc-java, try upgrade coc.nvim to latest release and coc-java to version 1.14.0.
