### ISSUE TITLE
http-timer package not found when installing/updating plugin

### ISSUE THREAD

**Issue by q12321q** [neoclide/coc-java#19]
Hello,
Used to use coc-json without any problem but today I tried to update the plugin and I got an error:

`CocInstall coc-java`
```
yarn add v1.10.1
warning package.json: No license field
warning No license field
[1/4] 🔍  Resolving packages...
error Couldn't find package "@szmarczak/http-timer@^1.1.2" required by "got@^9.6.0" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```
I have the same result if I do a `yarn add coc-java`.
Do you have any idea how I can fix that?
Thanks

**Comment by chemzqm** [comment]
Should be networks issue.

**Comment by q12321q** [comment]
I tried on 3 different networks :(
I manage to install http-timer manually by typing `yarn add "szmarczak/http-timer"` but it doesn't help me much:
```
yarn add v1.10.1
warning package.json: No license field
warning No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved 1 new dependency.
info Direct dependencies
└─ @szmarczak/http-timer@2.0.0
info All dependencies
└─ @szmarczak/http-timer@2.0.0
warning No license field
✨  Done in 2.09s.
```
I don't know if it's relevant or not.

**Comment by q12321q** [comment]
I found that: https://github.com/szmarczak/http-timer/issues/4
I'll give a try

**Comment by q12321q** [comment]
fixed by removing my `~/.npmrc`.
I should have something wrong there.
Sorry for the trouble.

**Comment by alumezi** [comment]
This happened to me today, in my case I had //registry.npmjs.org/:_authToken=... in ~/.npmrc file.
Removing "//" before the URL fixed the problem, can anyone explain some more on why does this happen.
And why do we get warned on this szmarczak/http-timer particular package.

**Comment by chemzqm** [comment]
Could be problem of old yarn version.
