### ISSUE TITLE
Annotations with Gradle

### ISSUE THREAD

**Issue by codyrioux** [neoclide/coc-java#191]
Hey coc-java devs,

This is more of a question than an issue but I noticed the README says that there is support for "Annotation processing support (automatic for Maven projects)". I read this as non-automatic for Gradle projects, how can this be manually executed for a Gradle project? Or am I reading this incorrectly and it is actually unsupported for Gradle?

Hoping to iron out the kinks using Lombok and coc-java together.

Thanks!

**Comment by dukcode** [comment]
I have same problem on gradle project. Did you solve the problem?

**Comment by codyrioux** [comment]
A few weeks ago I dug into the issue and it is definitely deeper at the language server level. The [eclise.jdt.ls](https://github.com/eclipse/eclipse.jdt.ls) also lists annotation processing as automatic for Maven projects. I did find some instructions on [Using Java Annotation Processors from Gradle and Eclipse](http://dplatz.de/blog/2018/gradle-apt.html) but haven't had the chance to try a solution yet.

**Comment by chemzqm** [comment]
Should be fixed on recent version of coc-java, try upgrade coc.nvim to latest release and coc-java to version 1.14.0.

Latest coc-java detect gradle and maven on your project.
