### ISSUE TITLE
Stop generating .project .classpath .settings/ files

### ISSUE THREAD

**Issue by ghost** [neoclide/coc-java#196]
This issue has already been solved in vscode-java in https://github.com/redhat-developer/vscode-java/pull/2153
and Eclipse JDT Language Server (eclipse.jdt.ls) in https://github.com/eclipse/eclipse.jdt.ls/pull/1900 and there
is even a blog post about it at https://devblogs.microsoft.com/java/say-goodbye-to-project-files-in-1-1-0

coc-java running on Vim (8.2) and Node.js (16.14.0) on Fedora Linux (35) still generates those files.

**Comment by tydaeru** [comment]
@[chemzqm](https://github.com/chemzqm) any insight on this?

**Comment by chemzqm** [comment]
Need some time to upgrade coc-java, I used to have issues with java environment on my machine and some components are missing from coc.nvim.

**Comment by chemzqm** [comment]
Should be fixed on recent version of coc-java, try upgrade coc.nvim to latest release and coc-java to version 1.14.0.
