### ISSUE TITLE
How to open java class in java library like vscode?

### ISSUE THREAD

**Issue by caiwenhn2008** [neoclide/coc-java#198]
Hi team, 
Is there any way to open a class in java library like vscode in NVIM with coc-java plugin?

<img width="879" alt="image" src="https://user-images.githubusercontent.com/6037646/161187257-bb0eaf6f-b354-4c52-8f29-fc6f5b420f4b.png">

**Comment by chemzqm** [comment]
CocList -I symbols

**Comment by caiwenhn2008** [comment]
excellent!! thanks
