### ISSUE TITLE
java.edit.organizeImports does not work

### ISSUE THREAD

**Issue by kabasakalis** [neoclide/coc-java#2]
When I see the list of available commands with `Denite coc-command`, `java.edit.optimizeImports` is available. If I  remove some of the imports that are used in code, executing `java.edit.optimizeImports` does nothing.Expected result would be to see the missing imports added.

**Comment by chemzqm** [comment]
`optimizeImports` does organize only, it doesn't fix your import.

**Comment by kabasakalis** [comment]
OK, but I tried changing the order of the imports and applied command, but nothing happens.
Also see vscode-java, it says that organize imports also adds missing imports:
https://github.com/redhat-developer/vscode-java/issues/490

**Comment by JulioJu** [comment]
Actually problem with jdt.ls was fixed (see https://github.com/eclipse/eclipse.jdt.ls/pull/856 ) But when I test with coc.nvim, it continue to no work.

@kabasakalis do you continue to have the same problem than me actually ?

**Comment by chemzqm** [comment]
@JulioJu It's codeAction, not command.
