### ISSUE TITLE
Resources Files in src cannot be auto synched to target folder for maven springboot project

### ISSUE THREAD

**Issue by caiwenhn2008** [neoclide/coc-java#200]
Hello,

I see home.html in resource folder can not be synched between src and target folder if i have any change in home.html.

I have to restart server or run "java.workspace.compile" with full mode. please help to check this issue, thanks.

<img width="292" alt="image" src="https://user-images.githubusercontent.com/6037646/162626709-48ca3db6-ea85-4ad0-ae26-3fed400c7e8a.png">

**Comment by chemzqm** [comment]
Should be issue with jdt.ls, the html files are not watched for changes, so full compile needed.
