### ISSUE TITLE
The autocompletion doesn't work with Maven dependencies

### ISSUE THREAD

**Issue by geeksilva97** [neoclide/coc-java#202]
I've got a Maven project and I would like to import classes using autocompletion as I do for internal Java classes. For example, if I started to type `StringBuilder` the dialog appears to me to import the classes from `java.lang`.

Would it work for maven dependencies? In that project, I have the `Apache HTTP Client` and would be great if when I start typing `HttpPost` the dialog appears to import from `org.apache.http.client.methods`

**Comment by chemzqm** [comment]
Configurations `java.completion.importOrder` `java.completion.favoriteStaticMembers` should helps.
