### ISSUE TITLE
Any help to solve the problem that causes `JDT Language server error Failed to import projects`?

### ISSUE THREAD

**Issue by geeksilva97** [neoclide/coc-java#203]
I've been searching to get more information on how to solve this but I couldn't find any solution so far. Also, the warning `[Java 16] [W] MyClass.java is a non-project file, only syntax errors are reported` is appearing.

I can't figure out how to solve this. I know I'm missing something, but I don't know what is. Sorry if it is such a silly question but I need help. Thanks.

**Comment by chemzqm** [comment]
See https://github.com/redhat-developer/vscode-java/wiki/%22Classpath-is-incomplete%22-warning.

Use `"java.errors.incompleteClasspath.severity": "ignore"` to avoid those diagnostics.
