### ISSUE TITLE
coc action support multiple values?

### ISSUE THREAD

**Issue by more-pepsi** [neoclide/coc-java#204]

**Comment by chemzqm** [comment]
Can't understand, what action?

**Comment by more-pepsi** [comment]
Any action. Take generating a constructor for example.

> Can't understand, what action?

**Comment by chemzqm** [comment]
We don't have multiple pick on old coc.nvim, will be added on new release.

**Comment by more-pepsi** [comment]
Just relised if you pick one you can pick again. ❤️
