### ISSUE TITLE
`java.codeGeneration.toString` settings are ignored

### ISSUE THREAD

**Issue by kmoschcau** [neoclide/coc-java#205]
Hi, I habe configured both the `codeStyle` and `template` sub settings in the above, but they are just simply ignored and the defaults are used instead. I also don't see anything in the Java server output that seems related.

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by kmoschcau** [comment]
I enabled trace, found the request and response. I looked through the request and the only parameters in there are the fields to generate for and the position in the file. There is no indication that any of the options are passed to the server.

**Comment by chemzqm** [comment]
Should be fixed on recent version of coc-java, try upgrade coc.nvim to latest release and coc-java to version 1.14.0.

The settings could be not recognized by your jdt.ls, from 1.14.0, coc-java comes with bundled jdt.ls,
