### ISSUE TITLE
where does The "java" server crashed 4 times in the last 3 minutes. message come from?

### ISSUE THREAD

**Issue by ssh352** [neoclide/coc-java#209]
[coc.nvim] The "java" server crashed 4 times in the last 3 minutes. The server will not be restarted.

I'd like to understand the issue better.
I wonder where this message comes from? is it from the jdtls or somewhere? where does it store the crash count? if I delete the file that stores the crash count, the problem would go away.

**Comment by theVerySharpFlat** [comment]
@ssh352 see #99 and #207

The solution (for me at least) seems to be to replace the downloaded jtdls with the latest milestone version at https://download.eclipse.org/jdtls/

**Comment by ssh352** [comment]
@theVerySharpFlat Thanks, except the solution, do you know where the crash count is stored?

**Comment by fannheyward** [comment]
@ssh352 https://github.com/neoclide/coc.nvim/blob/b5950acdbb4e6d36323085b10926b41eac245738/src/language-client/client.ts#L325

> if I delete the file that stores the crash count, the problem would go away.

No, you need to make jdtls to work.

**Comment by ssh352** [comment]
> @ssh352 https://github.com/neoclide/coc.nvim/blob/b5950acdbb4e6d36323085b10926b41eac245738/src/language-client/client.ts#L325
> 
> > if I delete the file that stores the crash count, the problem would go away.
> 
> No, you need to make jdtls to work.

Thanks Now I fully understand the issue. My manual restart of vim incremented the "crash count" and coc tracked it.

**Comment by daniellillja** [comment]
Downloading the latest tarball worked for me - you can run `:echo coc#util#extension_root().'/coc-java-data/server'` to find where to extract the files

**Comment by kwangyel** [comment]
is this a bug using the latest snapshot build?

**Comment by theVerySharpFlat** [comment]
Yes, I believe so. I tried to fix this in #207

**Comment by kwangyel** [comment]
@theVerySharpFlat yes seems like your merge would resolve the issue. 😁

**Comment by dapt4** [comment]
> @ssh352 see #99 and #207
> 
> The solution (for me at least) seems to be to replace the downloaded jtdls with the latest milestone version at https://download.eclipse.org/jdtls/

this works for me.

**Comment by chemzqm** [comment]
Should be fixed on recent version of coc-java, try upgrade coc.nvim to latest release and coc-java to version 1.14.0.

Latest coc-java comes with bundled jdt.ls
