### ISSUE TITLE
Getting massive cpu usage 

### ISSUE THREAD

**Issue by more-pepsi** [neoclide/coc-java#212]
```
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
```

osx. in standardspring project using 300% of cpu. Not at inital load, but after being opened in vim for a couple of days.

its the coc index.js that seems to do a load of processing

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.

Could be issue when globing files, should be fixed now.
