### ISSUE TITLE
Error on notification "formatSelected": formatRange provider not found for current buffer, your language server doesn't support it.

### ISSUE THREAD

**Issue by burg1ar** [neoclide/coc-java#213]
![image](https://user-images.githubusercontent.com/3461895/180737637-adbd4686-73e4-489b-8452-a9ba74c0eb56.png)

coc.nvim configs in `.vimrc`:
```vimrc
xmap <leader>f  <Plug>(coc-format-selected)
nmap <leader>f  <Plug>(coc-format-selected)
```

`coc-format-selected` is not working, error output:
Error on notification "formatSelected": formatRange provider not found for current buffer, your language server doesn't support it.

**Comment by chemzqm** [comment]
Should be fixed on recent version of coc-java, try upgrade coc.nvim to latest release and coc-java to version 1.14.0.

Range format is support by jdt.ls bundled with coc-java from 1.14.0
