### ISSUE TITLE
eclipse.jdt.ls now requires Java 17

### ISSUE THREAD

**Issue by NoahTheDuke** [neoclide/coc-java#214]
As seen [here](https://github.com/eclipse/eclipse.jdt.ls/issues/2117) and [here](https://github.com/eclipse/eclipse.jdt.ls/pull/2118), eclipse.jdt.ls 1.13 onward now requires Java 17. This should probably be noted in the README, and maybe even checked by coc-java and a better error message thrown than just "server restarted 4 times" and then the log shows "Error code 13".

**Comment by msbatarce** [comment]
Man.... I was fighting with this error for 2 hours. If it had been written in the README I would had been over with this in minutes

**Comment by chemzqm** [comment]
Should be fixed on recent version of coc-java, try upgrade coc.nvim to latest release and coc-java to version 1.14.0.

From 1.14.0, coc-java comes with bundled jdt.ls, the same as vscode-java
