### ISSUE TITLE
Doubt about workspaces

### ISSUE THREAD

**Issue by amgodoi** [neoclide/coc-java#216]
Hi,

Sometimes I edit a single java file using coc-vim and I am getting a message like this:
TestJava.java "is not on the classpath of project ...

Inside a maven project with "packages" everything is OK, but in single files without "packages" that massage always appears.

I tried ":CocCommand java.clean.workspace" but it did not work. I have a lot of maven projects and I try to "clean" the workspace frequently. 

Is there any workspace management using coc-vim? Any tip about it?

**Comment by chemzqm** [comment]
Checkout `:h coc-workspace`, when you open a single java file that belongs to other workspace, the jdt.ls would not found correct classpath for the new file. It's limitation of language server and this extension.

Use single workspace folder for one vim session is recommanded.

**Comment by chemzqm** [comment]
Use `"java.errors.incompleteClasspath.severity": "ignore"` to avoid the diagnostic message.

**Comment by amgodoi** [comment]
Thanks!!!

"coc-*" is a great plugin ... thanks a lot!
