### ISSUE TITLE
Language Support for Java client: couldn't create connection to server

### ISSUE THREAD

**Issue by TroyCode3** [neoclide/coc-java#221]
### I encountered this error after installing coc-java
![image](https://user-images.githubusercontent.com/88051085/187431157-80d648a0-b0d7-4742-8e1e-44f91d7156f1.png)

### Here's my settings and plugins
![image](https://user-images.githubusercontent.com/88051085/187431641-c017a798-58a4-46f0-b730-a8b46fffe816.png)
![image](https://user-images.githubusercontent.com/88051085/187431687-99d313eb-b239-4a1d-986e-ddf4200bf98a.png)

### Here's my coc settings
![image](https://user-images.githubusercontent.com/88051085/187431774-7638e121-7996-4896-ad62-4b3c8768c2f5.png)

**Comment by chemzqm** [comment]
Looks like the java version doesn't mean server's requirement, the code of coc-java need update.

**Comment by TroyCode3** [comment]
So is it considered a bug? Or can I do something to work around?

**Comment by chemzqm** [comment]
Try different java version

**Comment by TroyCode3** [comment]
Thank you. It worked.
