### ISSUE TITLE
Shortenings works incorrectly

### ISSUE THREAD

**Issue by IBugraGezer** [neoclide/coc-java#225]
When i use shortenings like "sout" or "serr", it writes "SSystem" instead of "System"

https://user-images.githubusercontent.com/72858973/191960021-3a43eb5c-8296-4af0-bb66-3fcd3e2ab326.mp4

**Comment by codebysandwich** [comment]
i have the same questiion

**Comment by codebysandwich** [comment]
I used <kbd>Ctrl</kbd> + <kbd>y</kbd> or trigger `coc#pum#confrim()` completed `sout [LS]`, appeared **SSystem.out.println({cursor});** 😭

**Comment by fastbyt3** [comment]
Facing the same issue.

**Comment by codebysandwich** [comment]
> Facing the same issue.
maybe, try this solution.
https://github.com/neoclide/coc-java/issues/218#issuecomment-1278411350

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.

The language server returns bad text edit range on completion resolve
