### ISSUE TITLE
[Question] Project growth schema

### ISSUE THREAD

**Issue by webdavis** [neoclide/coc-java#23]
Hello,

Thank you for this great plugin. I was wondering if you would be open to implementing a project growth schema? Something like a "critical features" milestone and another milestone for "nice-to-haves", attaching issues for the things you don't have time to implement yourself with `help_wanted`. Then just refer folks to a `CONTRIBUTING.md`, or something like that.

The reason I ask is because I can see myself wanting to get involved with this in my free time, and I think something along those lines would be really helpful.

**Comment by chemzqm** [comment]
The extension is a fork of https://github.com/redhat-developer/vscode-java, since I don't write java, I just try to keep this extension uptodate with vscode-java when a new release is available.

Will have a `CONTRIBUTING.md`.

**Comment by webdavis** [comment]
Ah perfect. Apparently I am a selective reader. I see that's at the top of your `README.md`. Thank you for the direction.
