### ISSUE TITLE
Autocomplete issues

### ISSUE THREAD

**Issue by racecraftr** [neoclide/coc-java#233]
The language server has two main issues, in my opinion:

1) Whenever i use the `sout~` completion, it always adds an extra "S" to the start - resulting in `SSystem.out.println`. 
2) Say that I have a class like this:
```java
class Foo {
}

```
I want to add a new line to write code inside the class, so I go to the left curly brace `{` and hit enter. But for some reason, this is what the extension does: 
```java
class Foo{

}
}
```
again, very annoying. (This also happens for functions, by the way.)
Is there any way to fix this?

**Comment by chemzqm** [comment]
Can't reproduce any of them, try upgrade your coc.nvim and use minimal vimrc.

**Comment by Taz03** [comment]
the first one happens for me as well, and i have no idea y

**Comment by chemzqm** [comment]
> the first one happens for me as well, and i have no idea y

Fixed on latest release branch of coc.nvim.

**Comment by chemzqm** [comment]
For second issue, please try minimal vimrc.
