### ISSUE TITLE
java.inlayHints.parameterNames works incorrectly

### ISSUE THREAD

**Issue by codebysandwich** [neoclide/coc-java#238]
<img width="569" alt="image" src="https://user-images.githubusercontent.com/32191093/215303965-d353861b-3250-4c60-962a-d5275e6b32f8.png">

inlayhints shows end of line, whether should showing at start of param?

**Comment by fannheyward** [comment]
You're using nvim, which can only show at the end of line. Try vim 9:

<img width="313" alt="截屏2023-01-29 11 59 06" src="https://user-images.githubusercontent.com/345274/215304144-02683e49-7166-46a7-9f84-15562b14ed64.png">

**Comment by codebysandwich** [comment]
> You're using nvim, which can only show at the end of line. Try vim 9:
> 
> <img alt="截屏2023-01-29 11 59 06" width="313" src="https://user-images.githubusercontent.com/345274/215304144-02683e49-7166-46a7-9f84-15562b14ed64.png">

thanks for your answer :) i will try it
