### ISSUE TITLE
[Feature] package refactor

### ISSUE THREAD

**Issue by Taz03** [neoclide/coc-java#239]
Is it possible to get support for package renaming?

**Comment by chemzqm** [comment]
Seems no such kind support, see https://github.com/redhat-developer/vscode-java/blob/master/document/_java.learnMoreAboutRefactorings.md

**Comment by laktak** [comment]
@chemzqm Could you take a look at this? Would it be possible to support this feature?

https://github.com/redhat-developer/vscode-java/issues/823
> Renaming a folder in the explorer view now triggers package refactoring.

https://github.com/redhat-developer/vscode-java/pull/1403
>  Refactor package name from file explorer #1403

**Comment by chemzqm** [comment]
> [@chemzqm](https://github.com/chemzqm) Could you take a look at this? Would it be possible to support this feature?
> 
> [redhat-developer/vscode-java#823](https://github.com/redhat-developer/vscode-java/issues/823)
> 
> > Renaming a folder in the explorer view now triggers package refactoring.
> 
> [redhat-developer/vscode-java#1403](https://github.com/redhat-developer/vscode-java/pull/1403)
> 
> > Refactor package name from file explorer #1403

It's supported on coc-java https://github.com/neoclide/coc-java/blob/master/src/fileEventHandler.ts#L19, but the file creation and rename should make use of API from workspace
https://github.com/neoclide/coc.nvim/blob/master/src/workspace.ts#L576
https://github.com/neoclide/coc.nvim/blob/master/src/workspace.ts#L597
Don't know if coc-explorer make use of them, or you can create coc extension and use those API.

**Comment by laktak** [comment]
Thank you for pointing me in the right direction! If this is already supported I'll [try to use watchman](https://github.com/neoclide/coc.nvim/wiki/Install-coc.nvim#install-watchman-for-file-watching)

**Comment by chemzqm** [comment]
> Thank you for pointing me in the right direction! If this is already supported I'll [try to use watchman](https://github.com/neoclide/coc.nvim/wiki/Install-coc.nvim#install-watchman-for-file-watching)

It's not related to watchman, the file operation need to be performed by APIs from `workspace` module of coc.nvim
