### ISSUE TITLE
Coc-java error on WSL

### ISSUE THREAD

**Issue by AxewBoTX** [neoclide/coc-java#244]
Check out [this](https://www.reddit.com/r/neovim/comments/10zqlgd/i_use_ubuntu_on_windows_using_wsl2_and_whenever_i/) reddit post by me for more context.
I use Ubuntu on WSL2 and before this I used to use neovim on windows for everything. And at that time everything was running good but after I switched to WSL whenever I open a java file in neovim I get bunch of errors.
Check the video in post to see all the errors.
Idk what to do. PLEASE HELP ME! HOW TO FIX THIS?!?!

**Comment by Stark-X** [comment]
Try uninstalling `coc-java`, remove its data directory (`~/.config/coc/extensions/coc-java-data` by default), then reinstalling it. Once you've done that, open a new simple java project, if you're luck, the error should disappear.
