### ISSUE TITLE
Add option to disable automatic comment completion

### ISSUE THREAD

**Issue by idanarye** [neoclide/coc-java#25]
Typing `/*` in a `.java` file with this plugin installed automatically completes the `*/`. I tried various plugin settings that look relevant but couldn't find a way to turn this of.

Can you add a setting to disable this automatic completion?

**Comment by chemzqm** [comment]
It's required for comment completion, PR welcome https://github.com/neoclide/coc-java/blob/master/src/index.ts#L408.
