### ISSUE TITLE
Code generation is not respecting vim TAB configuration

### ISSUE THREAD

**Issue by amgodoi** [neoclide/coc-java#262]
When any code is generated (like add toString method), indentation inserts TABs instead of SPACES.

Vim configuration:

set tabstop=4
set softtabstop=4
set shiftwidth=4 
set expandtab
set smarttab
set smartindent
set autoindent

Should code generation insert SPACES with this configuration?

Am I missing some coc-java configuration?

**Comment by chemzqm** [comment]
Should be problem of jdt.ls checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by amgodoi** [comment]
Hi!

For some reason after vim restart it worked.

Server Log:

![image](https://github.com/neoclide/coc-java/assets/78377022/77277f3f-0e60-4458-a95b-ed3665398853)

I think itś OK.

**Comment by chemzqm** [comment]
Could be buffer not saved to file.
