### ISSUE TITLE
when override method, how do i select these checkboxes.

### ISSUE THREAD

**Issue by PolygonT** [neoclide/coc-java#268]
![image](https://github.com/neoclide/coc-java/assets/56947591/c6db6f70-d731-4ca6-9e9f-91c7df3b5d1b)

**Comment by luocm03** [comment]
I've encountered the same problem, how did you solve that?
I checked the coc-java help doc, which says as below. But when I checked the key mapping one-by-one, there is no effect at all!
QuickPick related (available when created by |coc-dialog-quickpick|).

<C-f>               - scroll forward quickpick list.
<C-b>               - scroll backward quickpick list.
<C-j> <C-n> <down>  - move to next item in quickpick list.
<C-k> <C-p> <up>    - move to previous item in quickpick list.
<C-space>           - toggle selection of current item in quickpick list when
canSelectMany is supported.


<img width="907" alt="java浮动窗口下拉列表无法选择" src="https://github.com/user-attachments/assets/8231193d-df32-405b-85d2-20b73abc04d9">

**Comment by luocm03** [comment]
@PolygonT @chemzqm

**Comment by luocm03** [comment]
I find #4673，maybe help
