### ISSUE TITLE
Project Lombok

### ISSUE THREAD

**Issue by andys8** [neoclide/coc-java#27]
Currently there are errors because [Project Lombok](https://projectlombok.org/) is generating code, but this is not detected.

I was able to use the lombok with `w0rp/ale` by configuring the java executable path. It should also possible to set the param `-cp` in `coc-java` with `java.jdt.ls.vmargs` when it isn't overwritten.

https://github.com/w0rp/ale/issues/2242#issuecomment-478986885

For Vscode there is also: https://marketplace.visualstudio.com/items?itemName=GabrielBB.vscode-lombok

**Comment by andys8** [comment]
Okay, I figured it out. In case somebody has the same issue:

https://github.com/redhat-developer/vscode-java/wiki/Lombok-support describes configuration for vscode. It works the same way. It's important to avoid "~" and use the absolute path! See https://github.com/neoclide/coc.nvim/issues/650

### `coc-settings.json`
```json
{
  "java.jdt.ls.vmargs": "-javaagent:/usr/local/share/lombok/lombok-1.18.6.jar -Xbootclasspath/a:/usr/local/share/lombok/lombok-1.18.6.jar"
}
```

**Comment by ngocketit** [comment]
@andys8 's solution fixes Lombok issue but now coc-java doesn't show the errors any more (such as when there is a typo or syntax issue). Any ideas why?

**Comment by djb61230** [comment]
Yes it seems to know about the lombok get/set methods but no other parsing errors found when they exist.  Looking at the server log with: CocCommand java.open.serverLog - there might be a circular dependency problem:

17690 java.lang.NoClassDefFoundError: org/eclipse/jdt/internal/compiler/parser/Parser                                         
17691     at lombok.launch.PatchFixesHider$Transform.<clinit>(PatchFixesHider.java:181)                                       
17692     at org.eclipse.jdt.internal.compiler.parser.Parser.endParse(Parser.java:11688)         

And then later another stack trace:
17750 java.lang.NoClassDefFoundError: Could not initialize class lombok.launch.PatchFixesHider$Transform                      
17751     at org.eclipse.jdt.internal.compiler.parser.Parser.endParse(Parser.java:11688)                                      
17752     at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:12881)

**Comment by geeogi** [comment]
@andys8's solution enabled Lombok for me, but the normal JDT compilation started to fail. I was able to resolve this by removing the -Xbootclasspath flag, as described in [this comment](https://github.com/redhat-developer/vscode-java/issues/652#issuecomment-466906125). 

My `cos-settings.json` looks like this:

```
{
     "java.jdt.ls.vmargs": "-javaagent:/absolute/path/to/lombok.jar"
}
```

**Comment by georgbuechner** [comment]
Sorry, can anyone tell me, where I can find the coc-settings.json? Or if it does not exist, where to create ist? 

Maybe a few important notices.
OS manjaro
Editor nvim
I'm using coc and coc-java. 

It would be great to get some help on this. Its really annoying that lomboc does not work. As why applications sometime crash, when I edit a file, doe to getter/ setter not being recognized. which is really strange :D

**Comment by geeogi** [comment]
> Sorry, can anyone tell me, where I can find the coc-settings.json? Or if it does not exist, where to create ist?
> 
> Maybe a few important notices.
> OS manjaro
> Editor nvim
> I'm using coc and coc-java.
> 
> It would be great to get some help on this. Its really annoying that lomboc does not work. As why applications sometime crash, when I edit a file, doe to getter/ setter not being recognized. which is really strange :D

open nvim and type the `:CocConfig` command to edit `coc-settings.json`.

**Comment by muhammadFawzy** [comment]
Lombok not working for me and here is my configuration
```
  "java.jdt.ls.vmargs": "-javaagent:/{path}/lombok.jar -Xbootclasspath/a:{path}/lombok.jar -noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication",
```
any recommendation?
BTW tried to remove `-Xbootclasspath` but still not working

**Comment by Kirenai** [comment]
It worked for me in window 10 this way:

```JSON
"java.jdt.ls.vmargs": "-noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication --enable-preview -javaagent:\"c:\\Users\\..\\..\\lombok.jar\"",
```

No server execution error, JDT.

My current version of the JDT:  ``` jdt-language-server-1.2.0-202105210424.tar.rar ```

**Comment by igoracmelo** [comment]
Does anyone else get this nonsense errors?
```java
[Java 1610612976] [E] Syntax error, insert "Identifier (" to complete ConstructorHeaderName
```
![image](https://user-images.githubusercontent.com/85039990/160272396-4b00fc32-cec7-40a4-bdf0-ecf56407ae54.png)

**Comment by IlyasYOY** [comment]
I've created a simple script in python3 w/o dependencies: https://gist.github.com/IlyasYOY/7f5ec87c75d2c049eebe6b9c7cd4a066

PS. Now you can Lombok whenever you want!

**Comment by arcelio21** [comment]
@IlyasYOY  how your script is used?

**Comment by IlyasYOY** [comment]
> @IlyasYOY  how your script is used?

You can do run it using command: python3 script-file-name.py

**Comment by Taz03** [comment]
> @andys8's solution enabled Lombok for me, but the normal JDT compilation started to fail. I was able to resolve this by removing the -Xbootclasspath flag, as described in [this comment](https://github.com/redhat-developer/vscode-java/issues/652#issuecomment-466906125).
> 
> My `cos-settings.json` looks like this:
> 
> ```json
> {
>      "java.jdt.ls.vmargs": "-javaagent:/absolute/path/to/lombok.jar" 
> }
> ```
> 
> Download Lombok Jar from https://projectlombok.org/download.

so i did this but now the completion suggestions are super slow, sometimes it even times out. Any one else facing same issue? is there any fix? is it even caused by this?

**Comment by gummybuns** [comment]
I am unable to get coc-java to recognize my lombok annotations. i tried following the suggestions above and am also trying to just enforce lombok to be enabled, i have the following coc-settings:
```
  {                                                                                                                   
      "java.jdt.ls.vmargs": "-javaagent:/Users/gummybuns/work/java_projects/lombok-1.18.24.jar",                      
      "java.jdt.ls.lombokSupport.enabled": true,                                  
      "java.trace.server": "verbose"                                                                                                                               
  }
```

is there a recommended way to debug what is happening? 

There is a [troubleshooting section](https://github.com/neoclide/coc-java#troubleshooting) that provides suggestions for debugging coc-java, but there is just so much noise in some of these i dont even know what i am supposed to look for.


<img width="1063" alt="Screenshot 2023-05-24 at 4 37 44 PM" src="https://github.com/neoclide/coc-java/assets/47437711/603388e5-6b54-424b-aa16-62b22dc42afe">

**Comment by markleung123** [comment]
> I am unable to get coc-java to recognize my lombok annotations. i tried following the suggestions above and am also trying to just enforce lombok to be enabled, i have the following coc-settings:
> 
> ```
>   {                                                                                                                   
>       "java.jdt.ls.vmargs": "-javaagent:/Users/gummybuns/work/java_projects/lombok-1.18.24.jar",                      
>       "java.jdt.ls.lombokSupport.enabled": true,                                  
>       "java.trace.server": "verbose"                                                                                                                               
>   }
> ```
> 
> is there a recommended way to debug what is happening?
> 
> There is a [troubleshooting section](https://github.com/neoclide/coc-java#troubleshooting) that provides suggestions for debugging coc-java, but there is just so much noise in some of these i dont even know what i am supposed to look for.
> 
> <img alt="Screenshot 2023-05-24 at 4 37 44 PM" width="1063" src="https://private-user-images.githubusercontent.com/47437711/240735859-603388e5-6b54-424b-aa16-62b22dc42afe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MjY0NDUsIm5iZiI6MTcxNTYyNjE0NSwicGF0aCI6Ii80NzQzNzcxMS8yNDA3MzU4NTktNjAzMzg4ZTUtNmI1NC00MjRiLWFhMTYtNjJiMjJkYzQyYWZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDE4NDkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhNTE5MTQyZTE2OWMzNjc4ZDQxYTFmMjFiNjQwZGE1NWE2YzU4ODBhZjcyN2NhYjAxMjM5NzNiNmM4ZjdhYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FrB5jSzFrJhu2qPKAV1g0ic_QzOjGddJl2DgYr9hKC0">
> # Update
> idk man i guess they must have changed some things around between releases. This thread is the top search on google for lombok failures so here is what i did to fix i have no idea how someone else figured this out:
> 
> > Confirmed move lombok.jar to ~/.config/coc/extensions/node_modules/coc-java/lombok/lombok-{version}.jar fix the problem, and no need to configure lombok through java.jdt.ls.vmargs. I'm on Mac.
> 
> [Issue 240](https://github.com/neoclide/coc-java/issues/240)
> 
> That is exactly what i did (im on Mac too). i copied the `lombok-1.18.24.jar` into the directory. and it works now. Here is my coc-settings after that (pretty much no longer needed):
> 
> ```
>   {                                                                                                                           
>       "java.trace.server": "verbose"                                                                                          
>   } 
> ```

I am using mac but this is not working for me.
