### ISSUE TITLE
Embedded JRE and NixOS

### ISSUE THREAD

**Issue by trev-dev** [neoclide/coc-java#278]
The embedded JRE requires a system that adheres to the FHS standard.  NixOS is not one of those systems.  The documentation refers to a "universal" version.  Where may I find that?

**Comment by trev-dev** [comment]
Update: Explicitly setting "java.jdt.ls.java.home" to the nix store works, but we don't seem to be picking up what's set in `JAVA_HOME` any longer.

**Comment by asmodeus812** [comment]
What if you try `${env:JAVA_HOME}` does it work ?

**Comment by trev-dev** [comment]
That works, great suggestion @asmodeus812 :)
