### ISSUE TITLE
Additional directories with build-helper-maven-plugin are ignored

### ISSUE THREAD

**Issue by andys8** [neoclide/coc-java#29]
I've a project where code is generated and the location is defined with `build-helper-maven-plugin`. It's currently not recognized and therefore leads to errors for those imports.

#### pom.xml

```xml
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>generated-folder</id>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>${basedir}/src-gen/main/java</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

#### Related

https://github.com/redhat-developer/vscode-java/issues/177

**Comment by andys8** [comment]
@chemzqm I saw you added the `Can't fix` label. Is it that `vscode-java` has to fix the issue, and it's merged back into this project? Or is there a reason why it will not work?

**Comment by chemzqm** [comment]
Need vscode-java or jdt.ls fix this first.

**Comment by andys8** [comment]
Whoa, I'm happy and a bit embarrased. Found out it's actually working but the error's came from linters enabled by default from `w0rp/ale` instead. More information in this comment: https://github.com/redhat-developer/vscode-java/issues/177#issuecomment-508118291

Closing the issue. Sorry for the noise.
