### ISSUE TITLE
Coc-java not working on windows 10

### ISSUE THREAD

**Issue by yngwi** [neoclide/coc-java#33]
Hi,

I'm having problems in getting coc-java working on windows 10. Even when installed on an otherwise untouched windows 10 sandbox with only neovim, git, java 11 (adoptopenjdk), nodejs 12.8 installed, coc.nvim added with vim-plug and coc-java added as the only additional plugin, I get the following error message (in the language server output) when opening a Java file:

```
[Error  - 12:41:30] Starting client failed: 
TypeError: Cannot read property 'reader' of undefined
    at C:\Users\djell\.vim\plugged\coc.nvim\lib\language-client\client.js:2187:48
```

When trying the same on a comparable Ubuntu VM, everything works as expected. To the best of my knowledge, the environment (java, node) is set up correcly, JAVA_HOME points to the correct directory etc.

Kind regards,
Daniel

**Comment by HankelBao** [comment]
The exact same problem here on Windows.

**Comment by chemzqm** [comment]
Need log of coc.nvim https://github.com/neoclide/coc.nvim/wiki/Debug-coc.nvim

**Comment by yngwi** [comment]
Hi,

thanks for your reply!

Here is the log. It contains opening vim, opening a java file as part of a java project, waiting a bit and closing vim again.

[coc-nvim-8632.log](https://github.com/neoclide/coc-java/files/3595597/coc-nvim-8632.log)

I'm not sure what this line means, the folder and file definitely exists:
`2019-09-10T14:29:24.871 INFO (pid:8632) [language-client-index] - D:\Documents\Java\AdoptOpenJDK\jdk-11.0.3.7-hotspot\bin\java of java not exists`

![image](https://user-images.githubusercontent.com/963440/64614053-ec748780-d3d7-11e9-9ca9-7589609a72c0.png)

**Comment by chanhsiaoyu** [comment]
same here, but it's easy to workaroud. you can open ./config/coc/extension/node_module/coc-java/lib/index.ts.  search some thing like "/bin/java' and change it to "java.exe"
