### ISSUE TITLE
Where can I put the configurations?

### ISSUE THREAD

**Issue by fmv1992** [neoclide/coc-java#35]
Where can I put the configurations?

Where can I put the configurations given at:

https://github.com/neoclide/coc-java#supported-settings

Such as `java.completion.enabled`? In which file?

Thanks

**Comment by chemzqm** [comment]
Read wiki of coc.nvim

**Comment by fmv1992** [comment]
Thanks to point me to the documentation.

I had already read it before posting and still cannot find the correct
location.

I have tried:

1.  

    ```
    {
    "languageserver": {
        "metals": {
        "command": "metals-vim",
        "rootPatterns": ["build.sbt"],
        "filetypes": ["scala", "sbt"],
        "coc.preferences.colorSupport": false,
        "suggest.minTriggerInputLength": 3
        },
        "coc-java": {
            "java.completion.enabled": false
        }
    }
    }
    ```

1.  

    ```
    {
    "languageserver": {
        "metals": {
        "command": "metals-vim",
        "rootPatterns": ["build.sbt"],
        "filetypes": ["scala", "sbt"],
        "coc.preferences.colorSupport": false,
        "suggest.minTriggerInputLength": 3
        }
    },
    "java.completion.enabled": false
    }
    ```

Still completion shows up in both cases. If it is not heavily burdensome for
you I kindly ask again to give more elementary instructions for someone
learning how to use this plugin.

**Comment by fmv1992** [comment]
After some trial and error this format seems to be the correct one:

{
  "languageserver": {
    "metals": {
      "command": "metals-vim",
      "rootPatterns": ["build.sbt"],
      "filetypes": ["scala", "sbt"],
      "coc.preferences.colorSupport": false,
      "suggest.minTriggerInputLength": 3
    }
  },
  "java.trace.server": true,
  "java.autobuild.enabled": false,
  "java.completion.overwrite": false,
  "java.completion.enabled": false
}

These are picked up and changed if the config file changes:

```
!ENTRY org.eclipse.jdt.ls.core 1 0 2019-08-25 13:21:26.036 !MESSAGE >>New
configuration: {java={jdt={ls={vmargs=-noverify -Xmx1G -XX:+UseG1GC
-XX:+UseStringDeduplication}}, errors={incompleteClasspath={severity=warning}},
configuration={checkProjectSettingsExclusions=true,
updateBuildConfiguration=interactive}, trace={server=true},
import={gradle={enabled=true, wrapper={enabled=true}}, maven={enabled=true},
exclusions=[**/node_modules/**, **/.metadata/**, **/archetype-resources/**,
**/META-INF/maven/**]}, referencesCodeLens={enabled=false},
signatureHelp={enabled=false}, implementationsCodeLens={enabled=false},
format={enabled=true, comments={enabled=true}, onType={enabled=true,
fixComment={enabled=true}}}, autobuild={enabled=false},
maxConcurrentBuilds=1.0, completion={enabled=false, overwrite=false,
guessMethodArguments=false, favoriteStaticMembers=[org.junit.Assert.*,
org.junit.Assume.*, org.junit.jupiter.api.Assertions.*,
org.junit.jupiter.api.Assumptions.*, org.junit.jupiter.api.DynamicContainer.*,
org.junit.jupiter.api.DynamicTest.*, org.mockito.Mockito.*,
org.mockito.ArgumentMatchers.*, org.mockito.Answers.*], importOrder=[java,
javax, com, org]}, progressReports={enabled=true}, foldingRange={enabled=true},
maven={downloadSources=false},
codeGeneration={hashCodeEquals={useJava7Objects=false, useInstanceof=false},
useBlocks=false, generateComments=false, toString={template=${object.className}
[${member.name()}=${member.value}, ${otherMembers}],
codeStyle=STRING_CONCATENATION, skipNullValues=false, listArrayContents=true,
limitElements=0.0}}}}
```

However the completion popup always shows up (even with these configs). What seems to get disabled is the "tab completion feature".

Also the build error/suggestions are triggered even with `"java.autobuild.enabled": false`.

Is this the desired behavior?

**Comment by chemzqm** [comment]
It's problem of your vim configuration
