### ISSUE TITLE
The import com.foo.bar.baz cannot be resolved

### ISSUE THREAD

**Issue by BBonifield** [neoclide/coc-java#36]
I am getting module resolution errors from `coc.nvim` in my projects when the imports reference external modules.  When I open the same project using VSCode, Eclipse, or IntelliJ, I do not get the resolution errors.  I'm trying to root-cause why `coc-java` is having the issue with the language server when VSCode is not.  Do you have any tips regarding configuration that might be helpful?

**Comment by chemzqm** [comment]
Could be wrong workspaceFolder, checkout verbose output https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by chemzqm** [comment]
Use `:CocCommand java.project.addToSourcePath.command` to add custom folder to Java Source Path
