### ISSUE TITLE
Select multiple elements in "Generate Getters and Setters", "Generate Constructors" etc.

### ISSUE THREAD

**Issue by alvarosevilla95** [neoclide/coc-java#37]
Not sure if I'm missing something obvious, but it seems on the numbered lists you receive for actions such as "Generate Constructors", I'm unable to select multiple values, so I can only generate single argument constructors, or I have to generate getters/setters one by one.

**Comment by chemzqm** [comment]
Sorry, multiple selection is not implemented yet.

**Comment by patrickpichler** [comment]
Is there an open feature request for this in the coc.nvim project one can follow?
