### ISSUE TITLE
Add import on autocomplete as in vscode.

### ISSUE THREAD

**Issue by purpleP** [neoclide/coc-java#4]
In vscode when I autocomplete some type say `List` and it isn't imported yet it automatically imports it (and I can choose between ambiguous names right in autocomplete menu).

Can you make your extension to work as vscode in this regard?

**Comment by lockeadams** [comment]
This is unhelpful to your issue, but I have a related question: how can I manually import? I see no command for it and have not found anything in my searches.

**Comment by purpleP** [comment]
Code actions menu.

ср, 13 февр. 2019 г., 1:43 lockeadams <notifications@github.com>:

**Comment by chemzqm** [comment]
The language server returns:
```
        {
            "label": "List - java.util",
            "kind": 7,
            "sortText": "999999148",
            "filterText": "List",
            "insertText": "List",
            "data": {
                "decl_signature": "Ljava.util.List;",
                "pid": "15",
                "rid": "7",
                "uri": "file:///Users/chemzqm/eclipse-workspace/hello/src/hello/hello.java"
            }
        },
        {
            "label": "List - java.awt",
            "kind": 7,
            "sortText": "999999148",
            "filterText": "List",
            "insertText": "List",
            "data": {
                "decl_signature": "Ljava.awt.List;",
                "pid": "17",
                "rid": "7",
                "uri": "file:///Users/chemzqm/eclipse-workspace/hello/src/hello/hello.java"
            }
        },
```
But coc have to remove duplicated items with same label to do completion resolve, vim need to emit completion item change event to resolve this problem.

**Comment by purpleP** [comment]
> But coc have to remove duplicated items with same label **to do completion resolve**, vim need to emit completion item change event to resolve this problem.

To do what? I'm pretty sure old completion managers showed multiple items with the same name from different sources. Seems like it's possible to show completions with same name but different metadata.

**Comment by chemzqm** [comment]
> it's possible to show completions with same name but different metadata.

It can be shown, but I don't know which one is selected until CompleteDone, so that completion resolve can't work because it relies on the inserted text for now.

**Comment by purpleP** [comment]
@chemzqm Well you can remap `<C-n>` detect current completion item I guess...

**Comment by purpleP** [comment]
@chemzqm What do you call `comletion resolve`?

**Comment by chemzqm** [comment]
It's fixed now, coc not relay on inserted text any more.

**Comment by purpleP** [comment]
@chemzqm Thanks. Can I already check how this works?

**Comment by chemzqm** [comment]
> @chemzqm Thanks. Can I already check how this works?

Upgrade coc.nvim to v0.0.55

**Comment by purpleP** [comment]
@chemzqm Yay!
