### ISSUE TITLE
Complete for imported java class

### ISSUE THREAD

**Issue by rickywu** [neoclide/coc-java#40]
Works well for the method in the same project

![image](https://user-images.githubusercontent.com/442398/64947453-986e1500-d8a7-11e9-8a1c-d43a7359da41.png)

But if import com.github.pagehelper.PageHelper,
then I want to complete method for PageHelper, works well in IDEA, but not popup in coc-java

![image](https://user-images.githubusercontent.com/442398/64947473-a328aa00-d8a7-11e9-909c-71740aa21c1b.png)

This is IDEA
![image](https://user-images.githubusercontent.com/442398/64947534-ce12fe00-d8a7-11e9-93df-be478a94f172.png)

**Comment by chemzqm** [comment]
Could be the language server failed to load your .env file or it's getting too slow to response.

**Comment by rickywu** [comment]
@chemzqm 
Not sure where is the problem, see this issue https://github.com/eclipse/eclipse.jdt.ls/issues/967

I still have this problem even setup env var for Gradle

**Comment by chemzqm** [comment]
It works as expected for me, try checkout output from language server https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by rickywu** [comment]
[ls.zip](https://github.com/neoclide/coc-java/files/3618884/ls.zip)

I found one error about invalid path
[Error  - 9:50:38 AM] 2019-9-17 9:50:38 Initialization failed 
Failed to scan D:\emp
org.eclipse.core.runtime.CoreException: Failed to scan D:\emp

**Comment by rickywu** [comment]
I tried clean workspace but got error JDT Language Server error failed to scan D:\emp
the path is incorrect

**Comment by rickywu** [comment]
I runs on Windows and WSL for the same project, WSL works well, but not work on Windows
also compared the jvm args for jdt, seems it should be the problem of jdt probally.

**Comment by rickywu** [comment]
@chemzqm the same project but got diff rootPath, I think this is the problem

WSL:
---
    "rootPath": "/mnt/d/Work/ops",
    "rootUri": "file:///mnt/d/Work/ops",

Windows:
---
    "rootPath": "d:\\Work\\ops\\src\\main\\java\\com\\scrcu\\cangjie\\ops\\controller",
    "rootUri": "file:///d%3A/Work/ops/src/main/java/com/scrcu/cangjie/ops/controller",

**Comment by chemzqm** [comment]
Unlike vscode-java, coc-java doesn't have support for wsl.

**Comment by rickywu** [comment]
@chemzqm But WSL works well, Windows got invalid root path

**Comment by chemzqm** [comment]
Use command:

- `java.project.addToSourcePath.command: Add Folder to Java Source Path`: adds the selected folder to its project source path.

The workspace root resolve issue should be fixed on coc.nvim.
