### ISSUE TITLE
[Question] - Java - Using Lombok

### ISSUE THREAD

**Issue by rafaelnery** [neoclide/coc-java#45]
How configure **coc-java** to use https://projectlombok.org/ ?
Some idea?

**Comment by chemzqm** [comment]
Should be impossible for now.

**Comment by rafaelnery** [comment]
Works downloading lombok.jar from https://projectlombok.org and in `coc-settings.json`

```
{
  ...

  "java.jdt.ls.vmargs": "... -javaagent:[path_to_lombok.jar] -Xbootclasspath/a:[path_to_lombok.jar]
  ... 
}
```

**Comment by andys8** [comment]
Can confirm. Was working fine with @rafaelnery 's solution (see https://github.com/neoclide/coc-java/issues/27).
