### ISSUE TITLE
jdt.ls crashes with this plugin, works with vim-lsp

### ISSUE THREAD

**Issue by TheCycoONE** [neoclide/coc-java#47]
When I've tried to use coc-java, the server seems to never start up, and I end up with a number of log files in my working directory indicating errors.

The same versions of jdt.ls working with vim-lsp with the configuration below:
```
autocmd User lsp_setup call lsp#register_server({
    \ 'name': 'eclipse.jdt.ls',
    \ 'cmd': {server_info->[
    \   'java',
    \   '-Declipse.application=org.eclipse.jdt.ls.core.id1',
    \   '-Dosgi.bundles.defaultStartLevel=4',
    \   '-Declipse.product=org.eclipse.jdt.ls.core.product',
    \   '-Dlog.level=ALL',
    \   '-noverify',
    \   '-Dfile.encoding=UTF-8',
    \   '-Xmx1G',
    \   '-jar',
    \   expand('~/eclipse.jdt.ls/org.eclipse.jdt.ls.product/target/repository/plugins/org.eclipse.equinox.launcher_1.5.500.v20190715-1310.jar'),
    \   '-configuration',
    \   expand('~/eclipse.jdt.ls/org.eclipse.jdt.ls.product/target/repository/config_linux'),
    \   '-data',
    \   expand('~/eclipse.jdt.ls/workspace')
    \ ]},
    \ 'root_uri':{server_info->lsp#utils#path_to_uri(lsp#utils#find_nearest_parent_file_directory(lsp#utils#get_buffer_path(), 'build.gradle'))},
    \ 'whitelist': ['java'],
    \ })
```

Error logs that appear in the working directories with coc-java:
[hs_err_pid1726.log](https://github.com/neoclide/coc-java/files/3717778/hs_err_pid1726.log)
[hs_err_pid1748.log](https://github.com/neoclide/coc-java/files/3717779/hs_err_pid1748.log)
[hs_err_pid1776.log](https://github.com/neoclide/coc-java/files/3717780/hs_err_pid1776.log)
[hs_err_pid1805.log](https://github.com/neoclide/coc-java/files/3717781/hs_err_pid1805.log)
[hs_err_pid1832.log](https://github.com/neoclide/coc-java/files/3717782/hs_err_pid1832.log)

These errors were produced with the same jdt.ls. Before that I was using the default config / jdt.ls downloaded by the plugin with the same effect.

my coc-settings.json:
```json
{
  "languageserver": {
    "clangd": {
      "command": "clangd",
      "args": ["--background-index"],
      "rootPatterns": ["compile_flags.txt", "compile_commands.json", ".vim/", ".git/", ".hg/"],
      "filetypes": ["c", "cpp", "objc", "objcpp"]
    }
  },
  "java.jdt.ls.home": "/home/stephen/eclipse.jdt.ls",
  "java.trace.server": "verbose",
  "java.import.gradle.wrapper.enabled": true
}
```

Operating System: ArchLinux ARM
Arch: aarch64

**Comment by chemzqm** [comment]
No idea, it doesn't use your global jdt.ls, you can use configuration to use it

**Comment by TheCycoONE** [comment]
Based on your prior comment, I changed:
  `"java.jdt.ls.home"` to `"/home/stephen/eclipse.jdt.ls/org.eclipse.jdt.ls.product/target/repository"` which results in using the same paths, but still results in errors.

I agree it looks like an issue with the args.

**Comment by TheCycoONE** [comment]
Indeed, it works on this system if I don't use the G1 garbage collector:
` "java.jdt.ls.vmargs": "-noverify -Xmx1G",`
