### ISSUE TITLE
Logs contain `[object Object]` on startup

### ISSUE THREAD

**Issue by andys8** [neoclide/coc-java#48]
`toString` may be called instead of serializing the object (e.g. to json).

I think it could be this line.

https://github.com/neoclide/coc-java/blob/4593fcc449381c131aaee00999e865b29fac4a73/src/index.ts#L232

![image](https://user-images.githubusercontent.com/13085980/66720318-6a72e680-edfb-11e9-8148-40be863dc150.png)

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.
