### ISSUE TITLE
Class path cannot be resolved 

### ISSUE THREAD

**Issue by paroxayte** [neoclide/coc-java#5]
Description: On opening a java file in any maven project, the error `Classpath is incomplete. Only syntax errors will be reported:` is presented. Tested in multiple maven projects with valid pom.xml in project root. 

Relevant jdtls log snippet:

```
  !ENTRY org.eclipse.jdt.ls.core 1 0 2019-02-19 18:03:55.049
 45 !MESSAGE Classpath is incomplete. Only syntax errors will be reported for file:///home/azae/Dev/misc/heapSort/src/main/java/paroxayte/HeapSort.java
```

relevant ls output: `ls -l /home/azae/Dev/misc/heapSort/pom.xml` --> `-rw-rw-r-- 1 azae azae 1914 Dec 15 14:12 /home/azae/Dev/misc/heapSort/pom.xml`

Coc.nvim source: tag: v0.0.55

edit: I have also tried `:CocCommand java.projectConfiguration.update` with pom.xml as the active buffer. No change.

edit 2: I can get the plugin to work if and only if the first java project file I open is the pom.xml either by opening the pom first or `:CocRestart` when pom is the active buffer.

**Comment by chemzqm** [comment]
It should be the resolved project root is wrong, latest coc-java fixed this problem.
