### ISSUE TITLE
Second proposal

### ISSUE THREAD

**Issue by User-Hrsat** [neoclide/coc-java#50]
##### I have encountered the same problem 😥
> But there is a little different thing, I am using Linux.
I did a few tests, it seems that JDT will scan my root directory, some files will fail to scan when there are insufficient permissions or other files themselves.
At the same time, a new problem has arisen. The initialization time of the plugin is very long. Many friends around me are complaining about this matter.

- Some information flashed past my status bar, I tried to intercept this several times.
![](https://raw.githubusercontent.com/User-Hrsat/Reary/master/problem.png)

> It may be that you are collecting information about the problem.

#### So.Please solve the problem in time 😃

---

@chemzqm But WSL works well, Windows got invalid root path

If I use gvim open project on Windows, the messages like this:
---
D:\Work\ops
"src\main\java\com\xxx\controller\BlockIpController.java" [unix] 60L, 2198C
[coc.nvim] Using java from d:\Program Files\Java\jdk1.8.0_161\, version: 8
[coc.nvim] JDT Language Server starting at ops
[coc.nvim] JDT Language Server error Failed to scan D:\ops

Seems the JDT not work on the right workspace, that cause complete not works well

If chdir to project folder in vim, still got JDT Language Server error Failed to scan D:\ops

**Finally, I solved this problem by these steps**:
1. use teminal chdir to project folder, open gvim
2. open source files then JDT can scan for whole project correctly, then can complete for 3rd party class

The problem is I cannot use chdir in vim, otherwise will cause JDT scan failed error, so the rootPath detect mechanism and JDT parameter should be improved to support open project directly in vim when I need to change current workspace

_Originally posted by @rickywu in https://github.com/neoclide/coc-java/issues/40#issuecomment-532471774_

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc.nvim/wiki/Using-workspaceFolders make sure you have correct workspace folder resolved.

**Comment by User-Hrsat** [comment]
Yes!But it still has problems!
I can't use it in any directory, and the initialization is still very slow😥

**Comment by chemzqm** [comment]
The problem is the language server would scan too much files, so you have to make the workspace folder corrent.

**Comment by User-Hrsat** [comment]
OK. Thank you




On Tue, Oct 22, 2019 at 4:45 PM +0800, "Qiming zhao" <notifications@github.com> wrote:












The problem is the language server would scan too much files, so you have to make the workspace folder corrent.
