### ISSUE TITLE
Add posibility to only generate setters/getters

### ISSUE THREAD

**Issue by patrickpichler** [neoclide/coc-java#53]
As of right now, it is only possible to generate both getters and setters. There are some situations where this is not really wanted.

**Comment by chemzqm** [comment]
<img width="636" alt="Screenshot 2023-01-29 at 14 00 55" src="https://user-images.githubusercontent.com/251450/215308105-8071e0ae-48da-4156-b8da-cbc600f75527.png">
Should be fixed on recent version of coc-java, try upgrade coc.nvim to latest release and coc-java to version 1.14.0.
