### ISSUE TITLE
Left extra text when confirm completion condidates

### ISSUE THREAD

**Issue by beardnick** [neoclide/coc-java#55]
just write a simple String
![image](https://user-images.githubusercontent.com/25979613/68197641-8c741900-fff5-11e9-9979-64138902e322.png)
and fininally I get
![image](https://user-images.githubusercontent.com/25979613/68197672-94cc5400-fff5-11e9-9ea8-48ce1e94e82f.png)
nvim version :NVIM v0.5.0-23-gafd576ee9
confirm config: 
![image](https://user-images.githubusercontent.com/25979613/68197794-ce9d5a80-fff5-11e9-9c63-863f11eb7565.png)

the problem only happend for java language server candidates, it's fine for snippet,file,around condidates.

**Comment by chemzqm** [comment]
Please provide minimal vimrc.

**Comment by beardnick** [comment]
I create a debug config file. This is all the debug config.

```viml
if &compatible
    set nocompatible
endif

set runtimepath+=~/study/git/dein.vim
let g:dein_load_state = dein#load_state("~/study/git/debug/plugins")
if g:dein_load_state
    call dein#begin("~/study/git/debug/plugins")
    call dein#add("~/study/git/dein.vim")

    call dein#add('neoclide/coc.nvim',{'build':'./install.sh'})
endif
```

I just install coc.nvim with dein and install coc-java using coc.nvim.
It also produce the same problem.

**Comment by beardnick** [comment]
I thought I may find the problem. I removed my ~/.config/coc folder and just install coc-java, then everything worked fine. But after I installed coc-tabnine,the problem arose again. You may try to install coc-tabnine to reproduce it.

**Comment by haze** [comment]
@beardnick You can temporarily fix this by adding
```json
  "tabnine.disable_filetypes": [
    "java",
  ],
```
to your `cic-config.json`

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.
