### ISSUE TITLE
Can't properly uninstall

### ISSUE THREAD

**Issue by apertureless** [neoclide/coc-java#57]
Hello there!

I have an issue regarding uninstalling `coc-java`.

I am using a [neovim](https://github.com/GideonWolfe/vim.reaper) configuration which got `Coc` and `coc-java` included. I also raised an issue [there](https://github.com/GideonWolfe/vim.reaper/issues/3) but this might be related to `coc-java`. 

So `Coc` is installed over Plug. And various coc extensioned are installed:

<details>
 <summary>All extensions</summary>
```vim
 let g:coc_global_extensions = [
      \'coc-html', 
      \'coc-xml', 
      \'coc-java', 
      \'coc-ccls', 
      \'coc-powershell', 
      \'coc-r-lsp', 
      \'coc-vimlsp', 
      \'coc-lua', 
      \'coc-sql', 
      \'coc-go', 
      \'coc-css', 
      \'coc-sh', 
      \'coc-snippets',
      \'coc-prettier',
      \'coc-eslint',
      \'coc-emmet',
      \'coc-tsserver',
      \'coc-translator',
      \'coc-fish',
      \'coc-docker',
      \'coc-pairs',
      \'coc-json',
      \'coc-python',
      \'coc-imselect',
      \'coc-highlight',
      \'coc-git',
      \'coc-github',
      \'coc-gitignore',
      \'coc-emoji',
      \'coc-lists',
      \'coc-post',
      \'coc-stylelint',
      \'coc-yaml',
      \'coc-template',
      \'coc-tabnine',
      \'coc-utils'
      \]
```
</details>

I was always getting an interactive message output, because I do not have the java jdk installed.

```
The java.home variable defined in settings does not point to a JDK., Get the Java Development Kit?:
1. Yes
2. No
```
However, as I do not need the java part I simply uninstalled the coc-java package, removed it from the extenionlist and rebuild it.

## Steps taken:

- Remove `coc-java` from [plugin-settings.vim](https://github.com/GideonWolfe/vim.reaper/blob/master/nvim/configs/plugin-settings.vim#L275)
- Uninstall `coc-java` plugin `CocUninstall coc-java`
- Remove `java.home` from `coc-settings.json`
- Delete `.config/coc/extensions`
- Run `:CocRebuild`

However, I am still getting the propmt (now slightly different)

```
Java runtime could not be located, Get the Java Development Kit?:
1. Yes
2. No
```

Which I guess comes from `coc-java`, which should be uninstalled?

**Comment by fannheyward** [comment]
It’s `coc-xml`, which also need Java to run.

**Comment by chemzqm** [comment]
Use `:CocList extensions` for current extensions.

**Comment by apertureless** [comment]
@fannheyward Thanks! That was it. After removing the `coc-xml` extension, the message disappeared.
