### ISSUE TITLE
Syntax error highlighting using coc-java. Is it there?

### ISSUE THREAD

**Issue by Muzietto** [neoclide/coc-java#59]
I have installed coc.nvim and coc-java no problem on my machine (nodejs and Java were already there).

While editing .java files, I have all the code completion suggestions ok, but even if I type some random character I get no syntax errors signaled, neither I get them when I save the file.

I read that Coc supports "full language server protocol support as VSCode", and to me this means also syntax error detection and signaling.

Am I wrong to expect all this using coc-java? Is there some configuration I have to perform in order to obtain syntax error management?

Please note that I have _not_ modified my .vimrc as told in [the README](https://github.com/neoclide/coc.nvim#example-vim-configuration), because I found no reference to syntax error management.

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
