### ISSUE TITLE
Junit5 test execution from within neovim.

### ISSUE THREAD

**Issue by JSamir** [neoclide/coc-java#60]
Hi,

in Eclipse we can select methods/classes to be executed as Junit tests. This is very convenient for larger projects with many tests.

Currently I need to rebuild a test-jar every time I want to execute a new/changed test, which is very tedious compared to eclipse.

Is the JUnit5 integration in Eclipse part of the JDT, or is there any other way to execute JUnit tests without recompiling the whole package?

**Comment by chemzqm** [comment]
Check doc of jdt.ls.  Should be not supported, yet.

**Comment by JSamir** [comment]
Looks like we actually do not need it, because there is a command line launcher for JUnit:
https://junit.org/junit5/docs/current/user-guide/#running-tests-console-launcher

I have no idea how to do it in neovim, still too new, but in theory one can map a shortcut to a script/command which recompiles the current file and runs the command line launcher passing the class name as argument. This would be as fast as in eclipse I think.

Does not work for me right now because the launcher does not recognize my test classes, but that is not a coc-java issue.
