### ISSUE TITLE
coc-java randomly deleting sections of code when formatting on save

### ISSUE THREAD

**Issue by haze** [neoclide/coc-java#62]
is there a way to fix this? Is this an incompatibility with the auto format on save feature of coc? it's super annoying!

**Comment by haze** [comment]
[Here](https://imgur.com/5ZXkb9b) is a video of me repeatedly saving a file, indeterministic formatting...

**Comment by chemzqm** [comment]
Please provide verbose output from coc-java https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by haze** [comment]
I managed to solve this by using these:
```json
  "java.format.comments.enabled": true,
  "java.format.settings.url": "https://raw.githubusercontent.com/google/styleguide/gh-pages/eclipse-java-google-style.xml",
  "java.completion.overwrite": true,

```
