### ISSUE TITLE
format style does not work

### ISSUE THREAD

**Issue by douglarek** [neoclide/coc-java#66]
My coc java settings:
```
" coc java format settings.
let g:coc_user_config['java.format.comments.enabled'] = v:true
let g:coc_user_config['java.format.settings.url'] = 'https://raw.githubusercontent.com/google/styleguide/gh-pages/eclipse-java-google-style.xml'
let g:coc_user_config['java.completion.overwrite'] = v:true
```
It does not use GoogleStyle settings.

**Comment by chemzqm** [comment]
Please paste verbose output from jdt.ls

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by douglarek** [comment]
sorry, I found vscode-java does not work too.

**Comment by nicobao** [comment]
I faced the same issue, while eclipse jdt.ls logs was showing that the parameter was taken into account on startup.
I put the parameters in my coc-settings.json using :CocConfig however.
I removed my co-workers'Eclipse IDE-generated `.project` file and `.settings` folder from my working directory and then it worked.
