### ISSUE TITLE
jdtls syntax check with openjdk11 error

### ISSUE THREAD

**Issue by YuMu233** [neoclide/coc-java#67]
jdt.ls gives an error when I try the var syntax of jdk11

For example
 var test = "test";

**This is an error ** 
 `[Java 16777218] [E] var  cannot be resolved to a type` 

**My config** 

`call coc#config('java.home' , '/usr/lib/jvm/default')
call coc#config('java.configuration.maven.userSettings' , '/opt/maven/conf/settings.xml')
call coc#config('java.jdt.ls.vmargs' , '--add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED')` 

Jdtls seems to support jdk11 ,but i dont know how to config ,it seems to be a bug
i m sorry for my poor English :(

**Comment by chemzqm** [comment]
You need get support from https://github.com/eclipse/eclipse.jdt.ls, also you can checkout verbose output from jdt.ls https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
