### ISSUE TITLE
Can not disable comment format

### ISSUE THREAD

**Issue by douglarek** [neoclide/coc-java#69]
I use the latest coc-java with JDT.LS 0.52.0 , and this is my java settings:

```vimL
" coc java 设置
let g:coc_user_config['java.format.comments.enabled'] = v:false " 这里不工作!!!
let g:coc_user_config['java.saveActions.organizeImports'] = v:true
let g:coc_user_config['java.format.settings.url'] = 'https://raw.githubusercontent.com/google/styleguide/gh-pages/eclipse-java-google-style.xml'
let g:coc_user_config['java.format.settings.profile'] = 'GoogleStyle'
let g:coc_user_config['java.completion.overwrite'] = v:true
```
Same settings and jdt version when I use vscode-java work.

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by douglarek** [comment]
Hi @chemzqm , have you tried 0.52.0 ?

**Comment by chemzqm** [comment]
The configuration send to server as expected, it works as expected for me.
