### ISSUE TITLE
Failed to add class: Cannot nest

### ISSUE THREAD

**Issue by kozer** [neoclide/coc-java#7]
Hello, and thanks for the amazing job here!
I have the following problem in java projects.
When I open them i get the following error
```bash
[coc.nvim] Error output from java: Feb 22, 2019 7:13:25 PM Failed to add class
Cannot nest '/target/generated-sources/annotations' inside '/target/gene
rated-sources'. To enable the nesting exclude 'annotations/' from '/target/
generated-sources'
```
Can you please guide me to fix it somehow?
Thanks!

Some extra info:
```bash
## versions

vim version: NVIM v0.3.4
node version: v8.14.1
coc.nvim version: 0.0.55
term: screen-256color
platform: linux

```

**Comment by chemzqm** [comment]
I don't know what it means, you need help from jdt.ls team.

**Comment by chemzqm** [comment]
Checkout https://github.com/eclipse/eclipse.jdt.ls#feedback
