### ISSUE TITLE
java.action.organizeImports not found

### ISSUE THREAD

**Issue by fftyjw** [neoclide/coc-java#70]
My config is: 
map <leader>gi :call CocActionAsync('runCommand', 'java.action.organizeImports')<cr>

When I try to run the command java.action.organizeImports'',  I get this error message "Command: java.action.organizeImports not found"

**Comment by chemzqm** [comment]
You server not fully started https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel.

**Comment by fftyjw** [comment]
增加了详细日志，麻烦帮忙看看

**Comment by chemzqm** [comment]
只能说服务启动了，没啥调用时报找不到我就搞不懂了
