### ISSUE TITLE
[FEAT] Coc status integration

### ISSUE THREAD

**Issue by KarlWithK** [neoclide/coc-java#71]
Similar to the issue posted to coc-python (found here https://github.com/neoclide/coc-python/issues/138), I think it would be useful  if we can have a setting in package.json to change whether the 'JDT.LS' part appears in the statusbar. Personally, I been trying to turn it off is that it takes up too much space and changes my theme. Since this would go as a setting in package.json people can change it to their needs. 

Currently, this is what my setup looks like for example and in the bottom you can see what happens with the theme: 
![Selection_019](https://user-images.githubusercontent.com/31679231/76229967-6657c300-61f9-11ea-83a4-c67cb75e4ecb.png)

**Comment by chemzqm** [comment]
No, but you can create your own function for status line integration.
