### ISSUE TITLE
is there a way to jump onto parameter placeholders after function completion

### ISSUE THREAD

**Issue by rockneverdies55** [neoclide/coc-java#73]
After code completion e.g. `myObj.someFunction(${:param1}, ${:param2})`, I would like to be able to jump my cursor on function parameters (param1, param2, etc) to enter the actual values to be passed into the function.

Is there an easy way to accomplish that?

**Comment by chemzqm** [comment]
Read wiki of coc.nvim

**Comment by rockneverdies55** [comment]
:+1:   

```
let g:coc_snippet_prev = '<C-j>'
let g:coc_snippet_next = '<C-k>'
```
