### ISSUE TITLE
jdt.ls download files add md5 check-sum

### ISSUE THREAD

**Issue by fftyjw** [neoclide/coc-java#74]
Because download jdt.ls may spend a lot of time, user may close vim while downloading. And some of the depend jars may download fail or half downloaded . And coc-java can not detect this situation, therefor no tip messages is given when open a java file next time. 

Here is my situation, the org.eclipse.jdt.compiler.apt_1.3.800.v20190919-0948.jar which needed by jdt.ls is missing (can't find it in eclipse.org ether), cause jdt.ls start fail, and coc-java then try to start jdt.ls again and again，makes my computer cpu 100%. 

Maybe coc-java can gather all plugin needed in advance and record there md5s, then check wether they all download correctly or not on startup.   Also if jdt.js start failed for several times, do not try to start it again, just give a tip message about it would be nice.

**Comment by chemzqm** [comment]
PR welcome,
