### ISSUE TITLE
Can't change java.errors.incompleteClasspath.severity value

### ISSUE THREAD

**Issue by Edgardiez7** [neoclide/coc-java#76]
Hi, I can't seem to set java.errors.incompleteClasspath.severity default value to "ignore" so I dont get the warning "[Java 16] [W] Prueba.java is a non-project file, only syntax  errors are reported" when opening a single Java file.
Thats my coc config file and an example of the issue. Any ideas what I'm missing?

![issue](https://user-images.githubusercontent.com/46867372/77416308-0568e700-6dc4-11ea-94a7-da80306e590e.png)

**Comment by fannheyward** [comment]
Use `"java.errors.incompleteClasspath.severity":"ignore"`.

**Comment by Edgardiez7** [comment]
I love you, XD. Cant belive how thick I am at times.
