### ISSUE TITLE
Cant change java.errors.incompleteclasspath.severity 

### ISSUE THREAD

**Issue by Edgardiez7** [neoclide/coc-java#77]
Hi, I can't seem to set java.errors.incompleteClasspath.severity default value to "ignore" so I dont get the warning "[Java 16] [W] ... is a non-project file, only syntax errors are reported" when opening a Java file that isnt inside a project.
Thats my coc config file and an example of the issue. 
This config used to work in my Ubuntu setup and now that I changed to Arch it doesnt work anymore.
Any ideas what I'm missing?

![git](https://user-images.githubusercontent.com/46867372/77928280-82a2c900-72a8-11ea-8310-5b1b8354037e.jpg)

**Comment by chemzqm** [comment]
Looks like they're different things, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by Edgardiez7** [comment]
I think they are not, since that used to work in Ubuntu but doesnt work in Arch.

**Comment by chemzqm** [comment]
That warning has nothing to do with incomplete classpath.

**Comment by chemzqm** [comment]
You should check out output if you think the configuation not passed to server https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
