### ISSUE TITLE
Workspace symbols and tagFunc do not work with coc-java

### ISSUE THREAD

**Issue by rickysaurav** [neoclide/coc-java#80]
* CocList -I symbols  results in  :
     Error on "CocList symbols": Workspace symbols provider not found for current document
* with tagFunc=CocTagFunc , pressing <C-]> results in : 
      File does not exits

**Comment by chemzqm** [comment]
It's expected.

**Comment by rickysaurav** [comment]
Is there a way to get workspace symbols via jdt.ls in coc.nvim ? I think the language server supports workspaceSymbols.I have used it via emacs lsp-java previously. Is there a specific reason it doesn't work with coc.nvim?

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel.
You may using different version of jdt.ls or your emacs does workpsace symbols support without jdt.ls.

**Comment by rickysaurav** [comment]
I am using the latest release of jdt.ls, I am pretty sure emacs does not support workspace symbols of its own via lsp. I just tested workspace symbol with vscode-java, it seems to support workspace symbols. I'll try to post the communication traces via coc.nvim and vscode.

**Comment by chemzqm** [comment]
Hm, I found it's registered in request from jdt.ls.

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.

**Comment by rickysaurav** [comment]
Tested. Works as expected. Thanks for the prompt response. Cheers.

**Comment by rickysaurav** [comment]
Do we have a fix for CocTagFunc for coc-java or is it the expected behaviour?

**Comment by chemzqm** [comment]
`CocTagFunc` works as expected, try test goto definition feature first.
