### ISSUE TITLE
No diagnostic performed while typing.

### ISSUE THREAD

**Issue by Adityashaw** [neoclide/coc-java#81]
Coc-java isn't linting while I type. The only time it lints is when I save the file.
Trying since many days to perform : [Debug Language Server](https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel) but failing miserably.
Output of `:CocList services` looks bit strange : 
![vim_coc_java_services](https://user-images.githubusercontent.com/10658508/79698283-a18fec00-82a5-11ea-8f8c-6701a8afc9bf.png)
Nevertheless, I added `"Language Support for Java.trace.server" : "verbose"` to my coc-settings,json which makes it look like 
```
{
    "coc.preferences.extensionUpdateCheck" : "never",
    "diagnostic.refreshOnInsertMode": true,
    "diagnostic.checkCurrentLine": true,
    "diagnostic.displayByAle": false,
    "python.linting.enabled" : true,
    "python.linting.pylintArgs" : ["--load-plugins", "pylint-flask", "pylint-flask-sqlalchemy", "pylint-sqlalchemy"],
    "suggest.noselect": false,
    "suggest.autoTrigger": "always",
    "suggest.triggerAfterInsertEnter": true,
    "Language Support for Java.trace.server" : "verbose"
}
```
which is certainly wrong. I changed the last line to `"java.trace.server" : "verbose"`.
Writing `:CocCommand workspace.showOutput` shows a huge log. [click here to view](https://gist.github.com/Adityashaw/9ef36cb23aaab4c8f037585e23fe7b40)
I uploaded it and viewed on [Microsoft LSP Inspector](https://microsoft.github.io/language-server-protocol/inspector/) but I don't know what I should look for.
Any help to further progress the debugging would be divine. My goal is to make coc-java lint my java files (and display the diagnostic) while I type. 
Other Information : 
:CocInfo shows
```
## versions

vim version: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar  1 2020 17:21:03)
node version: v13.12.0
coc.nvim version: 0.0.78-312c7c4482
term: dumb
platform: linux

## Output channel: java

#skipping lines
#lines are the same as the huge log.
```
My [.vimrc](https://gist.github.com/Adityashaw/8ac76b0a7ab22601a831bdef4dbb126a)
If I am missing to add any information then please do tell.

**Comment by chemzqm** [comment]
Yes, pylint requires saved buffer to lint.

**Comment by Adityashaw** [comment]
> Yes, pylint requires saved buffer to lint.

**Pylint**???
Why is a *Python* Linter required for linting *Java* Files?
And it is mentioned in your 3rd row in "Features" : As you type reporting of parsing and compilation errors. Doesn't that mean linting while typing?

**Comment by chemzqm** [comment]
Could be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

Diagnostics only refreshed on insert leave by default, use `"diagnostic.refreshOnInsertMode": true` in coc-settings.json

**Comment by Adityashaw** [comment]
> Could be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

I have attached it in the first post itself. Can you please explain what exactly I need to find out from the output? The output is already attached in the first post.

> Diagnostics only refreshed on insert leave by default, use `"diagnostic.refreshOnInsertMode": true` in coc-settings.json

I have this line already. I have mentioned my `coc-settings.json` in the first post itself. Did I write it wrongly?

**Comment by chemzqm** [comment]
Search `textDocument/publishDiagnostics`, seems your server working as expected, but I don't know why you didn't get diagnostics.
