### ISSUE TITLE
Menu previews are not concealed.

### ISSUE THREAD

**Issue by BonaBeavis** [neoclide/coc-java#84]
How can I enable concealment for menu previews?

![Screenshot_2020-04-23_12-11-23](https://user-images.githubusercontent.com/3330855/80087746-d4630a00-855b-11ea-8334-8bbdc64838fb.png)

```vim
set nocompatible
filetype off

call plug#begin('~/.vim/bundle')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()

let g:python_host_prog = '/home/beavis/.virtualenvs/neovim/bin/python'
let g:python3_host_prog = '/home/beavis/.virtualenvs/neovim3/bin/python3'

syntax on
filetype plugin indent on
set hidden

set conceallevel=3
```

**Comment by chemzqm** [comment]
Checkout `:h CocOpenFloat`, it was set to 2 by default.

**Comment by BonaBeavis** [comment]
Ah, ok. conceallevel is set. But why does it only conceal "\`foo`" and not "**Parameters**" and links. In markdown files, those are concealed (with vim-markdown installed).
