### ISSUE TITLE
JDT Language Server error failed to scan /home/navi

### ISSUE THREAD

**Issue by Ivangonz** [neoclide/coc-java#85]
Having a hard time getting this set up and not sure if this is something to do with permissions to the folder or I don't have my java.home set up properly. I set up the JAVA_HOME variable to java-11-open-jdk but I can't figure out how to get it set up in coc-nvim settings.

**Comment by chemzqm** [comment]
Yes, because your home directory could contains too much files.
You should NOT use your home as working directory.

**Comment by darlingof02** [comment]
> Having a hard time getting this set up and not sure if this is something to do with permissions to the folder or I don't have my java.home set up properly. I set up the JAVA_HOME variable to java-11-open-jdk but I can't figure out how to get it set up in coc-nvim settings.

I get the same error. Have you solved it?

**Comment by chemzqm** [comment]
Many language server won't work at user's home.

**Comment by darlingof02** [comment]
> Many language server won't work at user's home.

Sorry, I still don't know how to solve it. Having read about similar situations in #50 , but I still have trouble understanding the word, "workspace".
