### ISSUE TITLE
.tooling folder in $HOME

### ISSUE THREAD

**Issue by braunbearded** [neoclide/coc-java#87]
Recently I have to develop some programs in Java. I was really surprised how easy it was to setup vim and coc for that matter to work with java, good job 👍. I noticed a new folder .tooling appeared in my home folder. This has probably something to with the the default language server or gradle I suppose. Is there any setting I missed or some environment variable to move that folder out of my home folder? 

For now I can tell that that it doesn't matter if I working on plain java file or on some bigger gradle project. The folder will be create every time. The folder contains a gradle folder with a versions.json which basically have a bunch of gradle versions in it. I am working on a Linux system.

**Comment by chemzqm** [comment]
`.tooling` is a gradle thing, you need check doc of gradle.
