### ISSUE TITLE
Getting command error "Internal Error" whenever I execute CocCommand java.lang.*

### ISSUE THREAD

**Issue by jaygazula27** [neoclide/coc-java#88]
**Versions**
vim version: VIM - Vi IMproved 8.2 8020803                                                                              
node version: v12.16.3                                                                                                  
coc.nvim version: 0.0.78-0c973a7a47
JDK: 14

**Steps to reproduce**

1. Create a basic maven project. No need to have any dependencies or anything complicated.
2. Create a simple Java class which simply prints something:
```
package com.sample;

public class App {

    public static void main(String[] args) {
        System.out.println("Hello World!");
    }
}
```
3. Execute the command `:CocCommand java.action.overrideMethodsPrompt` or `:CocCommand java.action.generateConstructorsPrompt` or basically anything with `java.action.*`.
4. Observe that the error `[coc.nvim] Command error: Internal error.` is printed.

**Relevant logs**
I turned on trace logging for Java, and I see the following printed in the logs (`:CocCommand workspace.showOutput`):
```
[Trace - 5:19:41 AM] Sending request 'java/listOverridableMethods - (1)'.
[Trace - 5:19:41 AM] Received response 'java/listOverridableMethods - (1)' in 15ms. Request failed: Internal error. (-32603).
Error data: "java.util.concurrent.CompletionException: java.lang.NullPointerException\n\tat java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)\n\tat java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)\n\tat java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)\n\tat java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)\n\tat java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)\n\tat java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)\n\tat java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)\n\tat java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)\n\tat java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)\nCaused by: java.lang.NullPointerException\n\tat org.eclipse.jdt.ls.core.internal.text.correction.SourceAssistProcessor.getInnovationContext(SourceAssistProcessor.java:456)\n\tat org.eclipse.jdt.ls.core.internal.text.correction.SourceAssistProcessor.getSelectionType(SourceAssistProcessor.java:451)\n\tat org.eclipse.jdt.ls.core.internal.handlers.OverrideMethodsHandler.listOverridableMethods(OverrideMethodsHandler.java:29)\n\tat org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$30(JDTLanguageServer.java:838)\n\tat org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:74)\n\tat java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)\n\t... 6 more\n"
```

When you trace through the code, it appears that it's failing with a null pointer exception [here](https://github.com/eclipse/eclipse.jdt.ls/blob/master/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/SourceAssistProcessor.java#L456). I'm unable to figure out if it's a bug with the Eclipse codebase or with coc-java.  
I'm assuming either `CodeActionParams params` is null or `params.getTextDocument()` is returning null.  

**Log files**

1. [`:CocCommand workspace.showOutput` log](https://github.com/neoclide/coc-java/files/4671516/coc.log)
2. [`:CocCommand java.open.serverLog` log](https://github.com/neoclide/coc-java/files/4671518/server.log)
3. [`:call coc#client#open_log()` log](https://github.com/neoclide/coc-java/files/4671520/coc-client-debug.log) (by following the steps [here](https://github.com/neoclide/coc-java/issues/82#issuecomment-617532696))

 
**Steps tried**
I've tried cleaning the workspace via `:CocCommand java.clean.workspace`. I've also tried reinstalling the CoC plugins from scratch (after removing JDT and any CoC configs). None of these methods worked.  
  
Please let me know if you need any other information.

**Comment by chemzqm** [comment]
Can't help, it's error from jdt.ls

**Comment by jaygazula27** [comment]
Thanks for the confirmation. It's interesting that nobody has reported this issue, which means maybe it's specific to my setup.

I can open a defect in their repo. But could you help me give them more information? I'm not too familiar with the internals of how the LSP calls are made, and so I was hoping you can tell me the entry point of these calls as well as any parameters passed in. Anything you believe might be helpful for them to fix this issue.

**Comment by chemzqm** [comment]
checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by jaygazula27** [comment]
@chemzqm I've been trying to debug this issue, and it may just be an issue with coc-java.
Here's what I found:

1. If you look at the `:CocCommand workspace.showOutput` log file attached to the original post, you'll see that the request `java/listOverridableMethods - (1)` has no params associated with it.

2. I modified sourceAction.ts [here](https://github.com/neoclide/coc-java/blob/3c914c2b9e154889361d2631cd2188cf7e5fa020/src/sourceAction.ts#L57) by simply printing out the params variable, and I saw that it was `undefined`.

3. I modified the registerOverrideMethodsCommand() by copying the logic from registerOrganizeImportsCommand(), specifically the assignment of the params variable. I simply added the following:
```
let doc = workspace.getDocument(workspace.bufnr)
let params: CodeActionParams = {
  textDocument: {
    uri: doc.uri
  },
  range: Range.create(0, 0, doc.lineCount, 0),
  context: { diagnostics: [] },
}
```
Once I added that snippet to registerOverrideMethodsCommand to ensure that the params variable is not undefined, everything works as expected.

So based on this, I do think it may be an issue on coc-java side.
Do you mind taking a look at this again please?

**Comment by chemzqm** [comment]
It should be codeAction, not command.

**Comment by jaygazula27** [comment]
@chemzqm oh damn, I'm a dummy. It works great now that I'm using it correctly. Thank you.
