### ISSUE TITLE
It does not understand java compiler options

### ISSUE THREAD

**Issue by duythaia8** [neoclide/coc-java#89]
I add following lines to pom.xml file and restart JDT server. But it still show errors when accessing javax.smartcardio

        <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
		  <version>3.8.1</version>
		  <configuration>
			  	<verbose>true</verbose>
				<fork>true</fork>
			  	<compilerArgs>
            		<arg>--add-modules</arg>
             		<arg>java.smartcardio</arg>
				</compilerArgs>
        </configuration>
        </plugin>
Does anybody have a way to make it understand java compiler options?

Thank you,
Duy

**Comment by mihaicristiantanase** [comment]
One, rather complicated way I managed to include, for example, `java.smartcardio` module, is with the following steps (for a Maven project):

1. Update `coc-settings.json` with `"java.import.maven.enabled": false`

This way `.classpath` is not going to be overriden.

2. Add this to project's `.classpath` (make sure it's the right JavaSE version):

```xml
<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-16">
  <attributes>
    <attribute name="module" value="true"/>
    <attribute name="limit-modules" value="java.se,jdk.accessibility,jdk.attach,jdk.compiler,jdk.httpserver,jdk.jartool,jdk.javadoc,jdk.jconsole,jdk.jdi,jdk.management,jdk.sctp,jdk.security.auth,jdk.security.jgss,jdk.unsupported,jdk.dynalink,jdk.jfr,jdk.jshell,jdk.jsobject,jdk.management.jfr,jdk.net,jdk.scripting.nashorn,jdk.unsupported.desktop,jdk.xml.dom,java.smartcardio,jdk.aot,jdk.charsets,jdk.crypto.cryptoki,jdk.crypto.ec,jdk.editpad,jdk.hotspot.agent,jdk.internal.vm.ci,jdk.internal.vm.compiler,jdk.internal.vm.compiler.management,jdk.jcmd,jdk.jdeps,jdk.jlink,jdk.jstatd,jdk.localedata,jdk.naming.dns,jdk.naming.rmi,jdk.pack,jdk.rmic,jdk.scripting.nashorn.shell,jdk.zipfs"/>
  </attributes>
</classpathentry>
```
(https://github.com/redhat-developer/vscode-java/issues/1561#issuecomment-670015455)

3. Run coc commands:

```
:CocCommand → clean workspace
:CocEnable
-- confirm that all is well or else
:CocRestart
:CocEnable
```

**Comment by chemzqm** [comment]
If you're using maven plugins, checkout https://github.com/redhat-developer/vscode-java/blob/master/document/_java.notCoveredExecution.md
