### ISSUE TITLE
Doesn't recognize imports in classpath on a simple project 

### ISSUE THREAD

**Issue by mdacach** [neoclide/coc-java#93]
coc-java doesn't seem to recognize my $CLASSPATH variable. 
https://algs4.cs.princeton.edu/code/
I followed these instructions to set my classpath.
If I do :echo $CLASSPATH inside vim I get everything correctly, if I compile anything from the classpath it also works as expectedly. But coc-java does not offer completion regarding the classpath files and throws errors at every import from it. 
This is a simple one file, not using anything.

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by mdacach** [comment]
I'm sorry could you help me some more. I didn't find anything wrong with the output.
Do you know how can I see what classpath the jdt.ls is using? or if I can change it with some command?

That's my relevant part in the code: 
`import edu.princeton.cs.algs4.WeightedQuickUnionUF; 
`
That is the settings it shows (I tried adding the classpath to the vmargs): 
https://pastebin.com/W1kcnSKb

And this is the error part: 
https://pastebin.com/z9CtsPta

It has a lot more lines but I don't think they are relevant, maybe this initial part here that has the errors too: 
https://pastebin.com/Xy7tMGZW

**Comment by mdacach** [comment]
Any help would be greately appreciated. I don't know my way around this stuff and couldn't find relevant information neither at the eclipse jdt page, or the vscode-java or anything

**Comment by mdacach** [comment]
Update: jdt will in fact not recognize your env classpath. 
To use jars from libraries you need to update the `java.project.referencedLibraries` 
Like this: https://github.com/redhat-developer/vscode-java/pull/1196#issuecomment-568192224

**Comment by you-n-g** [comment]
@mdacach 
I have similar issue. 
I've set `java.project.referencedLibraries` in `coc-settings.json` . 
![image](https://user-images.githubusercontent.com/465606/87877948-d3832c80-ca13-11ea-98fb-e67d5543a96f.png)

But it still raises the unresolve error.
![image](https://user-images.githubusercontent.com/465606/87878015-3c6aa480-ca14-11ea-8f4f-9e5df2577c3a.png)

Did you have similar problems ever? 


Thanks!

**Comment by you-n-g** [comment]
My problem is solved by configure the .classpath
![image](https://user-images.githubusercontent.com/465606/89660552-13974a00-d904-11ea-8fee-7932a5e607d2.png)

**Comment by vcavallo** [comment]
Same issue here for me.
I've also tried configuring a `.classpath` file - no help.

**Comment by AndreSouzaAbreu** [comment]
> My problem is solved by configure the .classpath
> ![image](https://user-images.githubusercontent.com/465606/89660552-13974a00-d904-11ea-8fee-7932a5e607d2.png)

Where is this file you have changed?

I tried changing the `.classpath` files in `~/.config/coc/extensions/coc-java-data/*/*/.classpath`, but after I change them and try using `vim` the changes are discarded and the files are the same as before.

**Comment by AndreSouzaAbreu** [comment]
I can't get the libraries of Princeton algs4 into working even after adding the path to the `java.project.referencedLibraries`

```json
"java.project.referencedLibraries": [
  "/home/andre/.local/share/algs4/algs4.jar",
  "/home/andre/.local/share/algs4/lift/lib/algs4.jar",
  "/home/andre/.local/share/algs4/lift/lib/introcs.jar",
  "/home/andre/.local/share/algs4/lift/lib/stdlib.jar",
]
```

Did any of you were able to get it working?
