### ISSUE TITLE
Do not close documentation while completing in insert mode

### ISSUE THREAD

**Issue by ChrisAmelia** [neoclide/coc-java#96]
This is related to https://github.com/neoclide/coc.nvim/issues/2102

This seems to happen only with Java so far, tested with Go completion and it works as expected.
Can be reproduced with these minimal configs:

init.vim
```vim
set runtimepath^=~/.local/share/nvim/plugged/coc.nvim
filetype plugin indent on
syntax on
set hidden

augroup mygroup
  " Update signature help on jump placeholder.
  autocmd User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')
augroup end
```

coc-settings.json
```json
"java.signatureHelp.enabled": true
```

**To reproduce**

1. Create a file Main.java with:

```java
public class Main {

    public static void main(String[] args) {
        String word = "Hello, World";
    }
}
```

2. Complete `word` with method `startsWith(String prefix, int offset)`:

```java
public class Main {

    public static void main(String[] args) {
        String word = "Hello, World";
        word.startsWith(
    }
}
```
 
Cursor is now positioned on the first parameter with documentation shown, as expected.  
Press any key, while in insert mode, and documentation disappears.

**Comment by chemzqm** [comment]
Should be fixed on coc.nvim.
